Repository Helixis/Paradise, pull requests merged in 2019-02, with the labels that each got.

#29 Map Backups
  _maps/map_backups/MinaGate.dmm
  config/example/away_mission_config.txt
Labels: Bugfix, Map changes

#30 Pequeños arreglos a los jobs
  code/game/jobs/access.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/security.dm
  code/game/jobs/jobs.dm
Labels: Balance, Tweak

#34 Zombies!
  code/HISPANIA/datums/diseases/virush.dm
  code/HISPANIA/modules/mob/language.dm
  code/HISPANIA/modules/mob/living/carbon/human/species/zombie.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/admin.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/disease.dm
  code/HISPANIA/modules/reagents/reagent_containers/bottle.dm
  code/HISPANIA/modules/surgery/organs/subtypes/zombie.dm
  code/datums/diseases/transformation.dm
  code/game/machinery/doors/airlock.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/_species.dm
  code/modules/mob/living/carbon/human/species/zombie.dm
  code/modules/mob/living/simple_animal/hostile/zombie.dm
  code/modules/reagents/chemistry/reagents/admin.dm
  code/modules/reagents/reagent_containers/bottle.dm
  paradise.dme
Labels: Balance, Bugfix, Feature, Tweak, WIP
