Repository Helixis/Paradise, pull requests merged in 2019-09, with the labels that each got.

#120 Actualización al código de los Murghal
  code/HISPANIA/modules/mob/language.dm
  code/HISPANIA/modules/mob/living/carbon/human/human.dm
  code/HISPANIA/modules/mob/living/carbon/human/species/murghal.dm
  code/HISPANIA/modules/surgery/organs/subtypes/murghal.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/surgery/organs/subtypes/murghal.dm
  goon/browserassets/css/browserOutput-dark.css
  goon/browserassets/css/browserOutput.css
  icons/hispania/mob/human_races/r_def_murghal.dmi
  icons/hispania/mob/human_races/r_murghal.dmi
  icons/hispania/mob/species/murghal/uniform.dmi
  icons/hispania/obj/species_organs/murghal.dmi
  icons/obj/surgery_murghal.dmi
  paradise.dme
  sound/hispania/effects/footsteps/sprint_murghal.ogg
  sound/hispania/effects/footsteps/sprint_murghal0.ogg
  sound/hispania/effects/footsteps/sprint_murghal1.ogg
Labels: Feature, Tweak

#122 Arreglo la oficina del CMO
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes

#123 Pequeño arreglo de las mascaras en el update_icon
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bugfix

#124 Energia en ciencias
  _maps/map_files/hispania/hispania.dmm
Labels: Bugfix, Map changes

#125 SpaceLube oops
  code/modules/reagents/chemistry/reagents/water.dm
Labels: Bugfix

#126 Arregla el bug de no poder abrir los airlocks con las manos
  code/game/machinery/doors/airlock.dm
Labels: Bugfix

#127 Arreglando mas errores del mapa en el dpt. Ciencias
  _maps/map_files/hispania/hispania.dmm
Labels: Bugfix, Map changes

#130 Pequeño buff a las Venus Trap
  code/HISPANIA/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
Labels: Tweak

#131 Limpieza del codigo
  SQL/paradise_schema.sql
  SQL/paradise_schema_prefixed.sql
  code/game/objects/items/weapons/kitchen.dm
  code/game/objects/random/random.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/floor/indestructible.dm
  code/game/turfs/simulated/floor/plating.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/spacesuits/ert.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/crafting/recipes.dm
  code/modules/customitems/item_defines.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/food/foods/meat.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/mining/explorer_gear.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
  code/modules/mob/living/carbon/human/species/voxarmalis.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/ammunition/special.dm
  code/modules/projectiles/guns/magic/wand.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/reagents/alcohol.dm
  code/modules/reagents/chemistry/reagents/drinks.dm
  code/modules/reagents/chemistry/reagents/food.dm
  goon/browserassets/css/browserOutput.css
  sound/goonstation/voice/zombie.ogg
  sound/goonstation/voice/zombiemuerde.ogg
Labels: Balance

#132 Hispania Icons Mob Refactorizado
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bugfix, Refactor

#135 Modifica las las cantidades de materiales de ciencias
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes, Tweak

#139 7 nuevas pastillas
  code/modules/client/asset_cache.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  icons/obj/chemical.dmi
Labels: Sprites

#133 Regresa los circuitos de teleciencias a RnD
  code/HISPANIA/modules/research/designs/comp_board_designs.dm
  code/HISPANIA/modules/research/designs/machine_designs.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/constructable_frame.dm
  paradise.dme
Labels: Feature

#138 Ropa de chef para gordos
  code/modules/clothing/suits/jobs.dm
  icons/mob/suit_fat.dmi
Labels: Sprites

#154 Aviso de baneos ingame
  code/modules/admin/topic.dm
Labels: Feature

#152 cambios a botanica
  code/datums/supplypacks.dm
  code/game/machinery/vending.dm
Labels: Tweak

#141 Los escudos dependen de que los uses en la mano activa
  code/game/objects/items.dm
  code/game/objects/items/weapons/shields.dm
  sound/hispania/effects/shieldactivehand.ogg
Labels: Feature

#155 Spacepox
  code/HISPANIA/datums/diseases/spacepox.dm
  code/modules/response_team/ert_outfits.dm
  paradise.dme
Labels: Feature

#158 Agrega una nueva bebida, hace que muchas bebidas de hispania sean bebidas alcoholicas [Por mazapan]
  code/HISPANIA/modules/reagents/chemistry/reagents/alcohol.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/drinks.dm
  code/HISPANIA/modules/reagents/chemistry/recipes/drinks.dm
  icons/hispania/obj/drinks.dmi
  icons/obj/drinks.dmi
Labels: Feature, Sprites, Tweak

#153 exosuit large syringe gun
  code/HISPANIA/game/mecha/equipament/tools/medical_tools.dm
  code/HISPANIA/modules/research/designs/mechfabricator_designs.dm
Labels: Feature

#149 Gadgets bag, Kitchen bag y shettsntcher
  code/HISPANIA/game/objects/items/weapons/storage/bags.dm
  code/HISPANIA/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/HISPANIA/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/machinery/vending.dm
  icons/hispania/obj/storage/storage.dmi
  paradise.dme
Labels: Feature, Sprites

#147 Modificación de Uniformes de Cap, Nueva maquina Wall drobe y trenchcoat para Capitán
  _maps/map_files/hispania/hispania.dmm
  code/HISPANIA/game/machinery/vending.dm
  code/HISPANIA/modules/client/preference/loadout/loadout_suit.dm
  code/HISPANIA/modules/clothing/head/jobs.dm
  code/HISPANIA/modules/clothing/suits/armor.dm
  code/HISPANIA/modules/clothing/suits/labcoat.dm
  code/HISPANIA/modules/clothing/under/jobs/civilian.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/hispania/mob/head.dmi
  icons/hispania/mob/suit.dmi
  icons/hispania/mob/uniform.dmi
  icons/hispania/obj/clothing/hats.dmi
  icons/hispania/obj/clothing/suits.dmi
  icons/hispania/obj/clothing/uniforms.dmi
  icons/hispania/obj/vending.dmi
  paradise.dme
Labels: Feature, Map changes, Sprites, Tweak

#162 Las armas de los mechas de combate tienen bloqueo de id
  code/modules/research/designs/mechfabricator_designs.dm
Labels: Balance, Tweak

#150 Engine goggles
  code/HISPANIA/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/HISPANIA/modules/clothing/glasses/engine_goggles.dm
  code/HISPANIA/modules/research/designs/equipment_designs.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/mining/equipment/mineral_scanner.dm
  icons/hispania/mob/eyes.dmi
  icons/hispania/mob/inhands/clothing_lefthand.dmi
  icons/hispania/mob/inhands/clothing_righthand.dmi
  icons/hispania/obj/clothing/glasses.dmi
  paradise.dme
Labels: Feature, Sprites

#170 Adiós feo return 1, hola sexy return TRUE.
  code/HISPANIA/modules/clothing/glasses/engine_goggles.dm
Labels: Tweak

#168 Menos pull más grab
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/mob/living/carbon/human/species/_species.dm
  code/modules/mob/living/living.dm
Labels: Feature, Tweak

#167 Nuevos -jobs objetives-
  code/HISPANIA/game/jobs/job_objectives/engineering.dm
  code/HISPANIA/game/jobs/job_objectives/science.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job_objectives/science.dm
  code/game/mecha/mecha_construction_paths.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/spacepods/construction.dm
  paradise.dme
Labels: Feature

#165 [Evento] Cambio de temperatura
  code/HISPANIA/modules/events/temperature_change.dm
  code/modules/events/event_container.dm
  icons/hispania/mob/screen_full.dmi
  paradise.dme
Labels: Feature

#159 Money Tree 2.0
  code/HISPANIA/modules/hydroponics/grown/money.dm
  code/game/machinery/vending.dm
  code/modules/hydroponics/grown/hispania-grown/coconut.dm
  icons/hispania/obj/hydroponics/growing_fruits.dmi
  icons/hispania/obj/hydroponics/harvest.dmi
  icons/hispania/obj/hydroponics/seeds.dmi
  icons/obj/hydroponics/hispania-growing_fruits.dmi
  icons/obj/hydroponics/hispania-harvest.dmi
  icons/obj/hydroponics/hispania-seeds.dmi
  paradise.dme
Labels: Feature, Sprites
