Repository Helixis/Paradise, pull requests merged in 2019-06, with the labels that each got.

#94 El cinturon de botanico puede llevar más variedad de cosas
  code/game/objects/items/weapons/storage/belt.dm
Labels: Tweak

#95 Hispania Box v2
  code/HISPANIA/game/machinery/jukebox.dm
  nano/templates/hispaniabox.tmpl
  sound/hispania/hispaniabox/binary.ogg
  sound/hispania/hispaniabox/fighter.ogg
  sound/hispania/hispaniabox/longday.ogg
  sound/hispania/hispaniabox/pianoman2.ogg
  sound/hispania/hispaniabox/road.ogg
  sound/hispania/hispaniabox/spaceref.ogg
  sound/hispania/hispaniabox/sweetly.ogg
  sound/hispania/hispaniabox/thriller.ogg
  sound/hispania/machines/dvd_working.ogg
Labels: Refactor, Tweak

#103 Retoque a la consola del HoP
  code/game/machinery/computer/card.dm
Labels: Tweak

#106 Agregar requerimientos mínimos de experiencia
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
  code/game/jobs/job/supervisor.dm
  code/game/jobs/job/support.dm
Labels: Tweak

#105 Accesos del Warden y RD restaurados
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Balance

#104 Quita los alts del trabajo ingeniero
  code/game/jobs/job/engineering.dm
Labels: Tweak

#84 Portea el Beamgunexosuit medical beamgun de tg.
  code/HISPANIA/game/mecha/equipament/tools/medical_tools.dm
  code/HISPANIA/modules/projectiles/guns/medbeam.dm
  code/HISPANIA/modules/research/designs/mechfabricator_designs.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  icons/hispania/mecha/mecha_equipment.dmi
  paradise.dme
Labels: Feature, Port, Sprites

#107 Roletimes
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/supervisor.dm
Labels: Tweak

#108 Los accesos del hop ahora se limitan a los de su trabajo en hispania
  code/game/jobs/job/supervisor.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
Labels: Balance

#100 Arepas
  code/HISPANIA/modules/food_and_drinks/food/foods/baked_goods.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_grill.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_microwave.dm
  icons/hispania/obj/food/food.dmi
Labels: Feature, Sprites

#112 Lets ripleys go fast in mining again.
  code/game/mecha/working/ripley.dm
Labels: Balance
