Repository Helixis/Paradise, pull requests merged in 2019-05, with the labels that each got.

#75 Fixes kiwi name and sprite
  code/HISPANIA/modules/mob/living/simple_animal/kiwi.dm
Labels: Bugfix, Tweak

#70 Tres nuevas bebidas, por Mazapán
  code/HISPANIA/modules/reagents/chemistry/reagents/drinks.dm
  code/HISPANIA/modules/reagents/chemistry/recipes/drinks.dm
  icons/hispania/obj/drinks.dmi
  icons/obj/drinks.dmi
  paradise.dme
Labels: Feature, Sprites

#71 Todos los Round Tips traducidos
  strings/tips.txt
Labels: Tweak

#83 Travis
  .travis.yml
Labels: Tweak

#82 Unusable emote 'babea'
  code/modules/mob/living/carbon/human/life.dm
Labels: Bugfix

#87 agrega iconos para cuando se tiene en la mano la xenobluecell y la xenobluemaker
  code/HISPANIA/modules/power/cell.dm
  icons/hispania/mob/inhands/items_lefthand.dmi
  icons/hispania/mob/inhands/items_righthand.dmi
Labels: Sprites

#90 Pequeño cambio al calentar Aceite -> Ash
  code/modules/reagents/chemistry/reagents/misc.dm
Labels: Tweak

#46 Añade tanques de plasma al protolathe.
  code/HISPANIA/game/objects/items/weapons/tanks/tank_types.dm
  code/HISPANIA/modules/research/designs/misc_designs.dm
  paradise.dme
Labels: Balance, Tweak

#92 Primer batch de lobby profile screens
  config/title_screens/images/4JCRHwM.jpg
  config/title_screens/images/7FwblbP.png
  config/title_screens/images/MIspmFe.png
  config/title_screens/images/RnW657E.jpg
  config/title_screens/images/Sv8tfJh.png
  config/title_screens/images/cc288de199a25488b8274cd190e182b5.png
  config/title_screens/images/eLavOLh.png
  config/title_screens/images/lU5GkaD.png
  config/title_screens/images/servicioleko.png
Labels: Feature
