Repository Helixis/Paradise, pull requests merged in 2019-12, with the labels that each got.

#192 Cambios al Wish Granter
  code/game/machinery/wishgranter.dm
Labels: Tweak

#188 Agrega nuevas recetas de miel.
  code/HISPANIA/modules/food_and_drinks/food/foods/baked_goods.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_microwave.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_oven.dm
  icons/hispania/obj/food/food.dmi
Labels: Feature, Sprites

#206 Aumenta el rango de la explosión objetivo del doppler array
  code/game/machinery/doppler_array.dm
Labels: Tweak

#184 Puke Emote
  code/modules/mob/living/carbon/human/emote.dm
Labels: Feature

#210 Sismologia espacial
  code/HISPANIA/game/machinery/constructable_frame.dm
  code/HISPANIA/game/machinery/doppler_array.dm
  code/HISPANIA/modules/research/designs/machine_designs.dm
  icons/hispania/obj/machines/research.dmi
  nano/templates/doppler_array_longrange.tmpl
  paradise.dme
Labels: Feature

#243 cambios al mechfabricator / arregla mi mierda
  code/game/mecha/mech_fabricator.dm
  code/modules/research/designs.dm
Labels: Bugfix, Tweak

#220 Comparte algunos diseños del protolathe con el mechfab
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/designs/medical_designs.dm
Labels: Tweak

#145 Arregla mi mierda - el hop puede usar su maquina de cuentas bancarias nuevamente. Jodete, codigo de paradise.
  code/game/jobs/job/supervisor.dm
  code/modules/economy/Accounts_DB.dm
Labels: Bugfix

#228 El hos y el cap pueden desactivar los protocolos de seguridad del protolathe y el mechfab
  code/HISPANIA/game/mecha/mech_fabricator.dm
  code/game/mecha/mech_fabricator.dm
  code/modules/research/rdconsole.dm
  paradise.dme
Labels: Feature

#224 Cambios al rechargestation.
  code/HISPANIA/game/machinery/rechargestation.dm
  code/game/machinery/rechargestation.dm
  paradise.dme
Labels: Feature

#185 NSS Hispania - Viales, pinturas para pod y consola de cuentas bancarias del hop
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes

#227 Add Crates
  code/HISPANIA/datums/supplypacks.dm
Labels: Feature

#237 Crew Pinpointer se puede llevar en el medical belt
  code/game/objects/items/weapons/storage/belt.dm
Labels: Tweak

#232 RnD rebalance
  code/HISPANIA/modules/research/designs/power_designs.dm
  code/modules/research/designs/power_designs.dm
  code/modules/research/designs/stock_parts_designs.dm
Labels: Tweak
