Repository Helixis/Paradise, pull requests merged in 2019-11, with the labels that each got.

#181 No más creación de energía de la nada: Protolathe/autolathe
  code/HISPANIA/modules/research/designs/power_designs.dm
  code/modules/research/designs/power_designs.dm
Labels: Tweak

#191 [listo] Cambios a la consola de RnD
  code/HISPANIA/modules/research/rdconsole.dm
  paradise.dme
Labels: Feature

#204 Resprite de las bodybags.
  code/game/objects/items/bodybag.dm
  icons/hispania/obj/bodybag.dmi
Labels: Port, Sprites

#171 Crea el exosuit medical beamgun
  code/HISPANIA/game/mecha/equipament/tools/medical_tools.dm
  code/HISPANIA/modules/projectiles/guns/medbeam.dm
  code/HISPANIA/modules/research/designs/mechfabricator_designs.dm
Labels: Balance, Tweak

#179 arregla la descripción del objetivo del CE
  code/HISPANIA/game/jobs/job_objectives/engineering.dm
Labels: Tweak

#205 Port de Femur Breaker
  code/HISPANIA/game/objects/structures/femur_breaker.dm
  code/HISPANIA/modules/crafting/recipes.dm
  icons/hispania/obj/femur_breaker.dmi
  paradise.dme
  sound/hispania/machines/femur_breaker.ogg
Labels: Port, Sprites

#186 [más que listo] Los tracking beacon son más utiles
  code/HISPANIA/game/mecha/mecha_control_console.dm
  code/game/mecha/mecha_control_console.dm
  code/game/mecha/medical/medical.dm
  code/game/mecha/working/working.dm
  paradise.dme
Labels: Balance, Tweak

#242 añade sprites inhand al plasmacutter avanzado
  code/modules/projectiles/guns/energy/special.dm
  icons/hispania/mob/inhands/guns_lefthand.dmi
  icons/hispania/mob/inhands/guns_righthand.dmi
Labels: Sprites

#194 [listo] Los satelites siempre están disponibles en cargo
  code/datums/supplypacks.dm
  code/modules/station_goals/shield.dm
Labels: Feature

#219 [listo]Ahora puedes sacar a un piloto de su mecha si tener que romper el mecha.
  code/game/mecha/mecha.dm
Labels: Feature, Tweak
