Repository Helixis/Paradise, pull requests merged in 2019-10, with the labels that each got.

#178 NSS Hispania actualizado y fixeado
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes

#189 [fix urgente] Energía en Ciencias 2
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes

#182 Cambios a la creación de baterias, toma 2.
  code/HISPANIA/modules/power/cell.dm
Labels: Tweak

#197 Fix hot_coco v3
  code/modules/food_and_drinks/drinks/drinks.dm
Labels: Fix

#209 Fabricar la Large Syringe Gun es más costoso
  code/HISPANIA/modules/research/designs/mechfabricator_designs.dm
Labels: Tweak

#212 Fix Semillas Hispania
  icons/hispania/obj/hydroponics/seeds.dmi
Labels: Bugfix

#222 arregla mi mierda (fix escudos -dos fix-)
  code/game/objects/items/weapons/shields.dm
Labels: Bugfix
