Repository Helixis/Paradise, pull requests merged in 2019-04, with the labels that each got.

#40 Firefighter goliath
  code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
Labels: Feature

#41 RDlargeroundcut_dark
  code/HISPANIA/modules/client/preference/loadout/loadout_suit.dm
  code/HISPANIA/modules/clothing/suits/labcoat.dm
  icons/hispania/mob/suit.dmi
  icons/hispania/obj/clothing/suits.dmi
Labels: Sprites

#42 Ume fuu multipage books
  code/HISPANIA/modules/library/lib_items.dm
  code/HISPANIA/modules/library/lib_machines.dm
  code/HISPANIA/modules/paperwork/paper_bundle.dm
  icons/obj/library.dmi
  paradise.dme
Labels: Feature, Tweak

#43 Hot drinks machine nerf - ready si es aprobado
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/reagents/chemistry/reagents/drinks.dm
  code/modules/reagents/chemistry/reagents/food.dm
Labels: Balance, WIP

#73 Añade corona de flores
  code/HISPANIA/modules/clothing/head/misc.dm
  code/HISPANIA/modules/crafting/recipes.dm
  icons/hispania/mob/head.dmi
  icons/hispania/obj/clothing/hats.dmi
  paradise.dme
Labels: Feature

#72 fix coco
  code/modules/food_and_drinks/drinks/drinks.dm
Labels: Bugfix

#74 añade el dm que debio ser añadido en el pr #67
  code/HISPANIA/modules/power/cell.dm
  paradise.dme
Labels: Bugfix
