Repository Helixis/Paradise, pull requests merged in 2020-02, with the labels that each got.

#275 OH VAYA UN PR SOBRE ARMAS!
  code/HISPANIA/game/mecha/equipament/tools/medical_tools.dm
  code/HISPANIA/modules/projectiles/ammo/energy.dm
  code/HISPANIA/modules/projectiles/guns/energy.dm
  code/HISPANIA/modules/projectiles/projectiles/beams.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/flamethrower.dm
  code/game/objects/items/weapons/holy_weapons.dm
  code/game/objects/items/weapons/pneumaticCannon.dm
  code/modules/admin/topic.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mining/lavaland/loot/ashdragon_loot.dm
  code/modules/mining/lavaland/loot/legion_loot.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/projectiles/ammunition/ammo_casings.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/gun_attachments.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/grenade_launcher.dm
  code/modules/projectiles/guns/magic.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/guns/projectile/toy.dm
  code/modules/projectiles/guns/rocket.dm
  code/modules/projectiles/projectile/reusable.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/surgery/organs/augments_arms.dm
  icons/hispania/mob/head.dmi
  icons/hispania/mob/inhands/clothing_lefthand.dmi
  icons/hispania/mob/inhands/clothing_righthand.dmi
  icons/hispania/mob/inhands/guns_lefthand.dmi
  icons/hispania/mob/inhands/guns_righthand.dmi
  icons/hispania/mob/suit.dmi
  icons/hispania/obj/clothing/hats.dmi
  icons/hispania/obj/clothing/suits.dmi
  icons/hispania/obj/guns/bayonets.dmi
  icons/hispania/obj/guns/energy.dmi
  icons/hispania/obj/guns/gun_temperature.dmi
  icons/hispania/obj/guns/magic.dmi
  icons/hispania/obj/guns/projectile.dmi
  icons/hispania/obj/guns/toy.dmi
  icons/mob/head.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
  paradise.dme
Labels: Balance, WIP

#288 w0w cinta policia y de ingenieria epica
  code/HISPANIA/modules/policetape.dm
  code/__DEFINES/layers.dm
  code/game/machinery/vending.dm
  icons/hispania/effects/hazard_tape.dmi
  icons/hispania/obj/policetape.dmi
  paradise.dme
Labels: Feature, Sprites

#333 Balance players para gameModes
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/cult/runes.dm
  code/game/gamemodes/nuclear/nuclear.dm
Labels: Balance

#301 Momento globos
  code/HISPANIA/game/objects/items/toys/Balloons.dm
  code/HISPANIA/modules/crafting/recipes.dm
  icons/hispania/mob/inhands/balloons_lefthand.dmi
  icons/hispania/mob/inhands/balloons_righthand.dmi
  icons/hispania/obj/balloons.dmi
  paradise.dme
Labels: Feature, WIP

#203 Nueva botella en la Vending del Bartender (Denme mi puto color)
  code/HISPANIA/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/alcohol.dm
  code/game/machinery/vending.dm
  icons/hispania/obj/drinks.dmi
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#330 Osos y Carpas (Balance del espacio)
  _maps/hispania.dm
  _maps/map_files/hispania/z6.dmm
  code/HISPANIA/game/objects/structures/spawner.dm
  paradise.dme
Labels: Balance

#361 Dracomeme
  code/HISPANIA/modules/food_and_drinks/food/foods/meat.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_microwave.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/alcohol.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/misc.dm
  code/HISPANIA/modules/reagents/chemistry/recipes/drinks.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  icons/hispania/obj/drinks.dmi
  icons/hispania/obj/food/food.dmi
  paradise.dme
Labels: Feature, Priority

#250 Containment Breach
  code/HISPANIA/game/gamemodes/miniantags/oldman/oldman.dm
  code/HISPANIA/game/gamemodes/miniantags/oldman/pocket_dimension.dm
  code/HISPANIA/modules/events/oldman.dm
  code/modules/events/event_container.dm
  icons/hispania/mob/oldman.dmi
  paradise.dme
  sound/hispania/effects/oldman/alert.ogg
  sound/hispania/effects/oldman/gasp1.ogg
  sound/hispania/effects/oldman/gasp2.ogg
  sound/hispania/effects/oldman/oldgrowl.ogg
  sound/hispania/effects/oldman/oldlaugh.ogg
  sound/hispania/effects/oldman/phasing.ogg
  sound/hispania/effects/oldman/sludge.ogg
  sound/hispania/effects/oldman/victim.ogg
Labels: Feature, WIP

#272 health analyzers quitados de medikits
  code/HISPANIA/modules/research/designs/medical_designs.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/modules/research/designs/autolathe_designs.dm
  paradise.dme
Labels: Port, WIP

#376 Añade las camas de Renault y Runtime
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes

#357 Colgate™
  code/HISPANIA/game/objects/items/miscellaneous/noose.dm
  code/modules/power/cable.dm
  icons/hispania/obj/miscellaneous.dmi
  paradise.dme
  sound/hispania/effects/noose_idle.ogg
  sound/hispania/effects/noosed.ogg
Labels: Feature

#304 Mas canciones
  code/HISPANIA/game/machinery/jukebox.dm
  sound/hispania/hispaniabox/Fly_Me_To_The_Moon.ogg
  sound/hispania/hispaniabox/Give_You_Up.ogg
  sound/hispania/hispaniabox/Golden_Wind.ogg
  sound/hispania/hispaniabox/Megalovania.ogg
  sound/hispania/hispaniabox/Tripaloski.ogg
  sound/hispania/hispaniabox/binary.ogg
  sound/hispania/hispaniabox/pianoman2.ogg
  sound/hispania/hispaniabox/road.ogg
  sound/hispania/hispaniabox/spaceref.ogg
  sound/hispania/hispaniabox/star_wars_cantina.ogg
  sound/hispania/hispaniabox/sweetly.ogg
  sound/hispania/hispaniabox/thriller.ogg
Labels: Sound

#384 Van 2 abejas y se cae la del medio.
  _maps/map_files/hispania/hispania.dmm
  code/HISPANIA/game/jobs/job/support.dm
  code/HISPANIA/game/objects/structures/hydroponics.dm
  code/game/jobs/job/support.dm
  code/game/machinery/telecomms/ntsl2.dm
  icons/hispania/obj/closet.dmi
  paradise.dme
Labels: Map changes

#388 Un PR completamente nuevo y original.
  _maps/map_files/hispania/hispania.dmm
  code/HISPANIA/modules/mob/living/simple_animal/friendly/dog.dm
  paradise.dme
Labels: Map changes, Wait

#393 La SILLA
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes, Wait

#358 New SuperSS13Market
  code/HISPANIA/defines/procs/newsounds.dm
  code/game/machinery/requests_console.dm
  paradise.dme
  sound/hispania/misc/announce1.ogg
Labels: Feature, Sound

#379 Esquilemos al zorro
  code/modules/mob/living/carbon/human/species/diona.dm
  code/modules/mob/living/simple_animal/friendly/diona.dm
  code/modules/surgery/organs/subtypes/diona.dm
Labels: Balance

#336 Nuevo Mob Lavaland: Plazmite (Versión Final)
  code/HISPANIA/game/objects/structures/lavaland/necropolis_tendril.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/meat.dm
  code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/plazmite.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/toxins.dm
  code/game/turfs/simulated/floor/asteroid.dm
  icons/hispania/mob/animals.dmi
  icons/hispania/obj/food/food.dmi
  paradise.dme
Labels: Feature

#415 Walldrobe(hos,ce,cmo)+fixsprite
  _maps/map_files/hispania/hispania.dmm
  code/HISPANIA/game/machinery/vending.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  icons/hispania/obj/closet.dmi
Labels: Map changes
