Repository Helixis/Paradise, pull requests merged in 2020-12, with the labels that each got.

#725 Momento Ropa, Cambia el Sprite del RD por uno mas bonito y le añade dos uniformes mas
  code/HISPANIA/game/machinery/vending.dm
  code/HISPANIA/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/medsci.dm
  icons/hispania/mob/species/grey/uniform.dmi
  icons/hispania/mob/species/vox/uniform.dmi
  icons/hispania/mob/uniform.dmi
  icons/hispania/obj/clothing/uniforms.dmi
  paradise.dme
Labels: Sprites, WIP

#765 Nuevas criaturas Lava Imp & shambling miner, Lavaland mobs.
  code/HISPANIA/game/objects/structures/lavaland/necropolis_tendril.dm
  code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/imp.dm
  code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/shamblingminer.dm
  code/game/turfs/simulated/floor/asteroid.dm
  icons/hispania/mob/lavaland/lavaland_monsters.dmi
  icons/hispania/obj/lavaland/artefacts.dmi
  paradise.dme
  sound/hispania/misc/impattacks.wav
  sound/hispania/misc/impdies.wav
  sound/hispania/misc/impinjured.wav
  sound/hispania/misc/impnearby.wav
  sound/hispania/misc/impranged.wav
  sound/hispania/misc/impsight.wav
  sound/hispania/misc/impsight2.wav
Labels: Feature

#789 But if you close your eyes It's like nothing changed at all
  code/modules/clothing/head/helmet.dm
  icons/hispania/mob/head.dmi
  icons/hispania/mob/inhands/clothing_lefthand.dmi
  icons/hispania/mob/inhands/clothing_righthand.dmi
Labels: Fix

#794 Bloody Kinetic Accelerator.
  code/game/machinery/wishgranter.dm
  code/hispania/modules/projectiles/guns/energy/kinetic_accelerator.dm
  icons/hispania/obj/guns/energy.dmi
  icons/hispania/obj/projectiles.dmi
Labels: Feature, Sprites

#786 Vida de los Goliath pero bien hecho
  code/__DEFINES/goliath.dm
  code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
  code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
  icons/mob/lavaland/lavaland_monsters.dmi
  paradise.dme
Labels: Feature, Sprites
