Repository Helixis/Paradise, pull requests merged in 2020-01, with the labels that each got.

#226 Nuevo objetivo para el botanico
  code/HISPANIA/game/jobs/job_objectives/hydroponics.dm
  code/game/jobs/job/support.dm
  code/modules/shuttle/supply.dm
  paradise.dme
Labels: Feature

#279 (Bug Fix) Batas invisibles sobre los Grey y Vox
  code/HISPANIA/modules/clothing/suits/labcoat.dm
Labels: Bugfix

#278 cambios al Rechargestation v2
  code/HISPANIA/game/machinery/rechargestation.dm
  code/game/machinery/rechargestation.dm
Labels: Tweak

#285 Nerfeo maquina de apuestas
  code/game/machinery/slotmachine.dm
Labels: Tweak

#255 welding goggles design
  code/HISPANIA/modules/research/designs/equipment_designs.dm
Labels: Feature

#256 fix hot_coco v4
  code/modules/reagents/chemistry/reagents/food.dm
Labels: Tweak

#293 Holidays
  code/HISPANIA/modules/holiday/holiday.dm
  code/modules/holiday/holiday.dm
Labels: Tweak

#282 FlamethrowerSound
  code/game/objects/items/weapons/flamethrower.dm
  sound/hispania/weapons/flamethrower.ogg
Labels: Sound

#239 Arregla la interacción las large grenades con los slime cores - fuck paradise
  code/HISPANIA/game/objects/items/weapons/grenades/custom_grenades.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/custom_grenades.dm
  paradise.dme
Labels: Bugfix

#238 No más creación de energía de la nada, versión extendida: Xenobluecell revenge
  code/HISPANIA/modules/power/cell.dm
  code/modules/power/cell.dm
  icons/hispania/obj/power.dmi
Labels: Balance, Sound, Sprites, Tweak

#274 cirugia con plasma
  code/modules/projectiles/guns/energy/special.dm
Labels: Balance

#294 fix uno
  code/HISPANIA/game/objects/items/miscellaneous/UNO.dm
Labels: Bugfix

#236 No más creación de energía de la nada: Capítulo final
  code/HISPANIA/modules/power/cell.dm
  code/game/machinery/recharger.dm
  code/game/machinery/rechargestation.dm
  code/game/mecha/equipment/tools/other_tools.dm
  code/game/mecha/mech_bay.dm
  code/modules/power/apc.dm
  code/modules/power/cell.dm
Labels: Balance

#215 Teleciencias Rework [ReTradis versión]
  code/HISPANIA/game/machinery/computer/buildandrepair.dm
  code/HISPANIA/modules/research/designs/comp_board_designs.dm
  code/HISPANIA/modules/research/designs/machine_designs.dm
  code/HISPANIA/modules/telesci/telesci_computer.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/constructable_frame.dm
  code/modules/telesci/telepad.dm
  code/modules/telesci/telesci_computer.dm
  paradise.dme
Labels: Balance, Feature, Refactor

#156 impresor de circuitos para ingenieros
  code/HISPANIA/game/machinery/constructable_frame.dm
  code/HISPANIA/modules/research/circuitprinter.dm
  code/HISPANIA/modules/research/designs/machine_designs.dm
  paradise.dme
Labels: Feature

#287 Crab rave
  code/modules/mob/living/simple_animal/friendly/crab.dm
  icons/hispania/mob/animals.dmi
Labels: Port, Sprites

#273 Vox rider , ups my bad
  code/modules/admin/verbs/vox_raiders.dm
Labels: Tweak

#244 medbeam refactor
  code/HISPANIA/game/mecha/equipament/tools/medical_tools.dm
  code/HISPANIA/modules/projectiles/guns/medbeam.dm
  code/HISPANIA/modules/research/designs/mechfabricator_designs.dm
  code/modules/projectiles/guns/medbeam.dm
Labels: Balance, Refactor

#251 ablative trenchcoat port
  _maps/map_files/hispania/hispania.dmm
  code/HISPANIA/modules/clothing/suits/miscellaneous.dm
  code/game/gamemodes/steal_items.dm
  code/modules/clothing/suits/armor.dm
  icons/hispania/mob/head.dmi
  icons/hispania/mob/inhands/clothing_lefthand.dmi
  icons/hispania/mob/inhands/clothing_righthand.dmi
  icons/hispania/mob/suit.dmi
  icons/hispania/obj/clothing/hats.dmi
  icons/hispania/obj/clothing/suits.dmi
  paradise.dme
Labels: Port

#259 Bluespace Roller Bed
  code/HISPANIA/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/HISPANIA/modules/research/designs/bluespace_designs.dm
  icons/hispania/obj/rollerbed.dmi
  paradise.dme
Labels: Feature

#240 Mutadone nerf
  code/modules/reagents/chemistry/reagents/medicine.dm
Labels: Balance

#233 El RPED update
  code/HISPANIA/game/objects/items/weapons/stock_parts.dm
  code/HISPANIA/game/objects/items/weapons/storage/bags.dm
  code/HISPANIA/modules/assembly/assembly.dm
  code/HISPANIA/modules/power/apc.dm
  code/HISPANIA/modules/power/cell.dm
  code/HISPANIA/modules/reagents/reagent_containers/glass_containers.dm
  code/HISPANIA/modules/telesci/bscrystal.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/machinery.dm
  code/game/machinery/rechargestation.dm
  code/game/objects/items/weapons/stock_parts.dm
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  paradise.dme
Labels: Feature

#302 cambios a delta 1/2
  _maps/delta.dm
  _maps/map_files/Delta/z2.dmm
Labels: Map changes

#252 Armaduras reactivas
  code/HISPANIA/modules/clothing/suits/reactive_armour.dm
  code/HISPANIA/modules/research/designs/equipment_designs.dm
  code/game/gamemodes/steal_items.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/assembly/signaler.dm
  code/modules/clothing/suits/armor.dm
  icons/hispania/obj/clothing/suits.dmi
  paradise.dme
Labels: Port

#248 "Energy Gun" para el Magistrado: The comeback
  code/HISPANIA/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/HISPANIA/modules/projectiles/ammo/energy.dm
  code/HISPANIA/modules/projectiles/guns/energy.dm
  code/game/gamemodes/steal_items.dm
  code/game/jobs/job/supervisor.dm
  icons/hispania/obj/guns/projectile.dmi
  paradise.dme
Labels: Balance, Feature

#313 El arte de la llama azul
  code/HISPANIA/game/jobs/job/blueshield.dm
  code/HISPANIA/modules/martial_arts/bscqc.dm
  paradise.dme
Labels: Feature

#213 IA shell port
  code/HISPANIA/game/data_huds.dm
  code/HISPANIA/game/objects/items/divices/radio/radio.dm
  code/HISPANIA/game/objects/items/robot/robot_upgrades.dm
  code/HISPANIA/modules/mob/living/silicon/ai/ai.dm
  code/HISPANIA/modules/mob/living/silicon/robot/robot.dm
  code/HISPANIA/modules/research/designs/mechfabricator_designs.dm
  code/__DEFINES/bots.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/shuttles.dm
  code/datums/wires/robot.dm
  code/game/machinery/transformer.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/examine.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/update_status.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/transform_procs.dm
  code/modules/projectiles/projectile/magic.dm
  icons/hispania/mob/actions/actions.dmi
  icons/hispania/obj/module.dmi
  paradise.dme
Labels: Port

#260 Mejoras al check_for_injuries Y el funcionamiento del CPR
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/species/_species.dm
Labels: Feature, Tweak
