Repository Helixis/Paradise, pull requests merged in 2020-10, with the labels that each got.

#671 Cambia color del texto "AGE RESTRINGED"
  code/modules/client/preference/preferences.dm
Labels: Fix, Tweak

#680 [Map Change] Sincronizar nuevas areas (Cyberiad)
  _maps/hispania.dm
  _maps/map_files/Delta/delta.dmm
  _maps/map_files/Delta/z2.dmm
  _maps/map_files/hispania/Lavaland.dmm
  _maps/map_files/hispania/hispania.dmm
  _maps/map_files/hispania/z2.dmm
  _maps/map_files/hispania/z6.dmm
  code/HISPANIA/defines/procs/newsounds.dm
  code/HISPANIA/game/objects/items/policetape.dm
  code/HISPANIA/game/objects/random/random.dm
  code/HISPANIA/modules/mob/living/silicon/ai/ai.dm
  code/HISPANIA/modules/mob/living/silicon/robot/robot.dm
  code/game/jobs/job/medical.dm
  code/game/machinery/camera/camera.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/space_management/zlevel_manager.dm
  paradise.dme
Labels: Feature, Fix, Map changes

#682 Cambia la edad mínima y restringe los jobs por edades
  code/__DEFINES/mobs.dm
  code/controllers/subsystem/jobs.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
  code/game/jobs/job/supervisor.dm
  code/game/jobs/job/support.dm
  code/game/jobs/job/support_chaplain.dm
  code/modules/client/preference/preferences.dm
  code/modules/mob/new_player/new_player.dm
Labels: Feature

#693 Travis SQL Test
  code/modules/client/preference/preferences.dm
  config/example/game_options.txt
Labels: Fix, Tweak

#697 Tweak Cambiar nivel de alarma como head
  tgui/packages/tgui/interfaces/CommunicationsComputer.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Tweak

#702 Fix Dream Checker
  code/HISPANIA/modules/mob/language.dm
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Fix

#699 Armadura de HoS alternativa estilo Desert Ranger/Los Angeles Riot suit.
  code/HISPANIA/game/machinery/vending.dm
  code/HISPANIA/modules/clothing/head/helmets.dm
  code/HISPANIA/modules/clothing/suits/armor.dm
  icons/hispania/mob/head.dmi
  icons/hispania/mob/suit.dmi
  icons/hispania/obj/clothing/hats.dmi
  icons/hispania/obj/clothing/suits.dmi
  paradise.dme
Labels: Feature, Sprites

#703 Add Sugerencias Varias de Discord
  code/game/jobs/job/engineering.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mining/machine_vending.dm
  code/modules/vehicle/ambulance.dm
  code/modules/vehicle/janicart.dm
Labels: Feature, Tweak

#705 Añadir un par de gorros a la Xtra.
  code/HISPANIA/game/machinery/vending.dm
Labels: Tweak

#709 Fix Sprites de Vending Machines
  code/HISPANIA/modules/clothing/head/helmets.dm
  code/HISPANIA/modules/clothing/head/jobs.dm
  code/HISPANIA/modules/clothing/suits/armor.dm
  code/HISPANIA/modules/clothing/suits/labcoat.dm
  code/HISPANIA/modules/clothing/under/jobs/civilian.dm
  code/HISPANIA/modules/clothing/under/jobs/security.dm
  icons/hispania/mob/uniform.dmi
Labels: Fix

#710 [Delta] Nueva Estación ¡Bienvenidos a Delta!
  _maps/delta.dm
  _maps/map_files/Delta/delta.dmm
  _maps/map_files/Delta/z2.dmm
Labels: Map changes

#706 Add Nuevas Latas de Soda
  code/HISPANIA/modules/food_and_drinks/drinks/drinks/cans.dm
  code/game/machinery/vending.dm
  icons/hispania/obj/drinks.dmi
  icons/obj/drinks.dmi
  paradise.dme
Labels: Feature, Sprites

#715 Tweak Flask a Loadout
  code/HISPANIA/modules/client/preference/loadout/loadout_general.dm
Labels: Tweak

#698 Add Nuevas Armas y Ampliaciones a SpacePods
  code/HISPANIA/modules/research/designs/spacepod_designs.dm
  code/HISPANIA/modules/spacepods/equipment.dm
  code/modules/spacepods/equipment.dm
  paradise.dme
Labels: Feature

#717 Tweak Multiplicador de Eventos
  code/modules/events/event_container.dm
Labels: Tweak

#704 Cambia el revolver del detective
  code/modules/projectiles/projectile/bullets.dm
Labels: Tweak
