Repository Helixis/Paradise, pull requests merged in 2020-11, with the labels that each got.

#721 Tweak Plant Bag
  code/game/objects/items/weapons/storage/bags.dm
Labels: Tweak

#713 [Map Change] Expansión a Libreria (Cyberiad)
  _maps/map_files/hispania/hispania.dmm
  code/HISPANIA/game/machinery/vending.dm
Labels: Map changes

#728 Add Nuevos Cortes de Pelo/Barba y un Tatuaje by Deep
  code/HISPANIA/modules/mob/new_player/sprite_accessories/human/human_body_markings.dm
  code/HISPANIA/modules/mob/new_player/sprite_accessories/human/human_facial_hair.dm
  code/HISPANIA/modules/mob/new_player/sprite_accessories/human/human_hair.dm
  icons/hispania/mob/sprite_accessories/human/human_body_markings.dmi
  icons/hispania/mob/sprite_accessories/human/human_facial_hair.dmi
  icons/hispania/mob/sprite_accessories/human/human_hair.dmi
  paradise.dme
Labels: Sprites

#729 Add Port Discount's Dan's
  _maps/map_files/hispania/hispania.dmm
  code/HISPANIA/game/machinery/vending.dm
  code/HISPANIA/game/objects/items/trash.dm
  code/HISPANIA/modules/food_and_drinks/food/condiments.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/other_snacks.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/food.dm
  icons/hispania/obj/food/containers.dmi
  icons/hispania/obj/food/food.dmi
  icons/hispania/obj/trash.dmi
  icons/hispania/obj/vending.dmi
  sound/hispania/misc/donkselfheat.ogg
Labels: Feature, Port

#723 Mueve los cambios a los vending de paradise a hispania.
  code/HISPANIA/game/machinery/vending.dm
  code/HISPANIA/game/objects/items/policetape.dm
  code/HISPANIA/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/alcohol.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/drinks.dm
  code/game/machinery/vending.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  icons/_nanomaps/Delta_nanomap_z1.png
Labels: Tweak

#736 Fix Detalles menores
  code/game/gamemodes/cult/runes.dm
  code/modules/admin/verbs/adminhelp.dm
Labels: Fix

#737 Balance Bubblegum
  code/modules/mining/lavaland/loot/bubblegum_loot.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
Labels: Feature, Port

#747 [Snow Planet: NAGA] Bases de Trabajo para prueba de rendimiento
  _maps/hispania_ice.dm
  _maps/map_files/RandomRuins/SpaceRuins/abandonedtele.dmm
  _maps/map_files/RandomRuins/SpaceRuins/abandonedzoo.dmm
  _maps/map_files/RandomRuins/SpaceRuins/asteroid1.dmm
  _maps/map_files/RandomRuins/SpaceRuins/asteroid2.dmm
  _maps/map_files/RandomRuins/SpaceRuins/asteroid3.dmm
  _maps/map_files/RandomRuins/SpaceRuins/asteroid4.dmm
  _maps/map_files/RandomRuins/SpaceRuins/asteroid5.dmm
  _maps/map_files/RandomRuins/SpaceRuins/blowntcommsat.dmm
  _maps/map_files/RandomRuins/SpaceRuins/clownmime.dmm
  _maps/map_files/RandomRuins/SpaceRuins/debris1.dmm
  _maps/map_files/RandomRuins/SpaceRuins/debris2.dmm
  _maps/map_files/RandomRuins/SpaceRuins/debris3.dmm
  _maps/map_files/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/map_files/RandomRuins/SpaceRuins/derelict1.dmm
  _maps/map_files/RandomRuins/SpaceRuins/derelict2.dmm
  _maps/map_files/RandomRuins/SpaceRuins/derelict3.dmm
  _maps/map_files/RandomRuins/SpaceRuins/derelict4.dmm
  _maps/map_files/RandomRuins/SpaceRuins/derelict5.dmm
  _maps/map_files/RandomRuins/SpaceRuins/dj.dmm
  _maps/map_files/RandomRuins/SpaceRuins/druglab.dmm
  _maps/map_files/RandomRuins/SpaceRuins/emptyshell.dmm
  _maps/map_files/RandomRuins/SpaceRuins/gasthelizards.dmm
  _maps/map_files/RandomRuins/SpaceRuins/golemtarget.dmm
  _maps/map_files/RandomRuins/SpaceRuins/intactemptyship.dmm
  _maps/map_files/RandomRuins/SpaceRuins/listeningpost.dmm
  _maps/map_files/RandomRuins/SpaceRuins/mechtransport.dmm
  _maps/map_files/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/map_files/RandomRuins/SpaceRuins/onehalf.dmm
  _maps/map_files/RandomRuins/SpaceRuins/spacebar.dmm
  _maps/map_files/RandomRuins/SpaceRuins/syndiecakesfactory.dmm
  _maps/map_files/RandomRuins/SpaceRuins/syndiedepot.dmm
  _maps/map_files/RandomRuins/SpaceRuins/turretedoutpost.dmm
  _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
  _maps/map_files/RandomRuins/SpaceRuins/ussp_tele.dmm
  _maps/map_files/RandomRuins/SpaceRuins/way_home.dmm
  _maps/map_files/RandomRuins/SpaceRuins/whiteship.dmm
  _maps/map_files/RandomRuins/SpaceRuins/wizardcrash.dmm
  _maps/map_files/hispania_ice/hispania_ice.dmm
  code/HISPANIA/game/area/Space Station 13 areas.dm
  code/HISPANIA/game/objects/effects/mapping_helpers.dm
  code/HISPANIA/game/turf/hispania_floor.dm
  code/__DEFINES/is_helpers.dm
  code/controllers/subsystem/mapping.dm
  code/game/area/ss13_areas.dm
  code/game/gamemodes/blob/blob.dm
  code/game/gamemodes/blob/theblob.dm
  code/game/gamemodes/cult/cult_items.dm
  code/game/gamemodes/miniantags/bot_swarm/swarmer.dm
  code/game/objects/structures/aliens.dm
  code/modules/map_fluff/hispania_ice.dm
  code/modules/mob/living/living.dm
  code/modules/space_management/space_level.dm
  code/modules/space_management/space_transition.dm
  code/world.dm
  paradise.dme
Labels: Feature

#748 [Snow Planet: Naga] Tormentas de Nieve, Gravedad, Plantas y Sprites
  _maps/hispania_ice.dm
  _maps/map_files/RandomRuins/SpaceRuins/asteroid3.dmm
  _maps/map_files/hispania/z2.dmm
  _maps/map_files/hispania_ice/hispania_ice.dmm
  code/HISPANIA/datums/weather/weather_types/naga_storm.dm
  code/HISPANIA/game/area/Space Station 13 areas.dm
  code/HISPANIA/game/objects/effects/mapping_helpers.dm
  code/HISPANIA/game/objects/structures/flora.dm
  code/HISPANIA/game/turf/hispania_floor.dm
  icons/effects/weather_effects.dmi
  icons/hispania/effects/weather_effects.dmi
  icons/hispania/obj/flora/flora_snow.dmi
  icons/hispania/obj/flora/small_flora_snow.dmi
  icons/hispania/turf/snow.dmi
  paradise.dme
Labels: Feature

#742 Sprites feos de armas adios, nuevos sprites feos de armas saludos.
  code/modules/clothing/head/helmet.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  icons/hispania/mob/head.dmi
  icons/hispania/mob/inhands/guns_lefthand.dmi
  icons/hispania/mob/inhands/guns_righthand.dmi
  icons/hispania/obj/clothing/hats.dmi
  icons/hispania/obj/guns/energy.dmi
  icons/hispania/obj/projectiles.dmi
Labels: READY FOR REVIEW

#753 Fix Area Missing y Recursos perdidos a ingeniería
  _maps/map_files/hispania/hispania.dmm
Labels: Fix

#738 Add Advanced Roller Bed
  code/HISPANIA/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/HISPANIA/modules/crafting/recipes.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/modules/response_team/ert_outfits.dm
  code/modules/surgery/helpers.dm
  icons/hispania/obj/rollerbed_adv.dmi
Labels: Tweak

#754 [Meta] Reparaciones Generales
  _maps/map_files/MetaStation/MetaStation.v41A.II.dmm
  _maps/map_files/MetaStation/z2.dmm
Labels: Fix, Map changes

#760 [Cyberiad] Fix Menores
  _maps/map_files/hispania/hispania.dmm
  code/HISPANIA/game/machinery/vending.dm
Labels: Fix

#758 Cursed Kinetic Crusher
  code/HISPANIA/modules/mining/equipment/kinetic_crusher.dm
  code/game/machinery/wishgranter.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  icons/hispania/mob/inhands/items_lefthand.dmi
  icons/hispania/mob/inhands/items_righthand.dmi
  icons/hispania/obj/kinetic_crusherc.dmi
  icons/hispania/obj/projectiles.dmi
  paradise.dme
Labels: Feature

#780 Mini-Buff al Resonator y Upgraded Resonator
  code/modules/mining/equipment/resonator.dm
Labels: Tweak
