Repository Helixis/Paradise, pull requests merged in 2020-04, with the labels that each got.

#576 Cambios en cargo, sin errores (espero)
  _maps/map_files/hispania/hispania.dmm
Labels: CONFLICT, Map changes

#548 Balance Vending Machines
  code/HISPANIA/game/machinery/vending.dm
  code/game/machinery/vending.dm
  code/modules/arcade/prize_datums.dm
Labels: Balance

#500 Ariete de Seguridad
  _maps/map_files/hispania/hispania.dmm
  code/HISPANIA/game/objects/items/weapons/melee/misc.dm
  icons/hispania/mob/inhands/items_lefthand.dmi
  icons/hispania/mob/inhands/items_righthand.dmi
  icons/hispania/obj/items.dmi
  sound/hispania/weapons/ram.ogg
Labels: Feature

#595 la chiclasion
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mining/lavaland/loot/bubblegum_loot.dm
  icons/hispania/mob/suit.dmi
  icons/hispania/obj/clothing/suits.dmi
Labels: Fix, Tweak

#600 Tweak JetPack Hardsuit Upgrade a Prolathe
  code/HISPANIA/modules/research/designs/equipment_designs.dm
Labels: Tweak

#580 [Map Changes] Brig-Phyisician Office (Cyberiad)
  _maps/map_files/hispania/hispania.dmm
  code/HISPANIA/game/objects/structures/crates_lockers/security.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Map changes

#614 Add Songs a JukeBox Abril (BACHATA)
  code/HISPANIA/game/machinery/jukebox.dm
  sound/hispania/hispaniabox/Golden_Wind.ogg
  sound/hispania/hispaniabox/Megalovania.ogg
  sound/hispania/hispaniabox/bachata.ogg
  sound/hispania/hispaniabox/cumbion.ogg
  sound/hispania/hispaniabox/fighter.ogg
  sound/hispania/hispaniabox/longday.ogg
  sound/hispania/hispaniabox/rock.ogg
  sound/hispania/hispaniabox/salsa.ogg
Labels: Priority, Sound

#606 Tweak Adicciones
  code/modules/reagents/chemistry/reagents/drinks.dm
  code/modules/reagents/chemistry/reagents/drugs.dm
Labels: Tweak

#618 cuchillos para todos
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
Labels: Tweak

#612 fix apcells
  _maps/map_files/Delta/delta.dmm
  _maps/map_files/hispania/hispania.dmm
  _maps/map_files/hispania/z6.dmm
Labels: Fix

#626 nerf a los fantasmos
  code/datums/spell.dm
  code/modules/mob/dead/observer/spells.dm
Labels: Administración, Priority, Refactor, Revert/Feature Removal

#599 no se que título ponerle, pero no es algo relevante (Pelo para los unathis)
  code/HISPANIA/modules/mob/new_player/sprite_accessories/human/human_hair.dm
Labels: Feature

#598 [New Clothes] Nuevos Uniformes, Berets y Hats para Sec officer y Pod Pilot, Nuevo sprite del Armor, Recolor a Chaqueta del Warden
  _maps/map_files/hispania/hispania.dmm
  code/HISPANIA/game/machinery/vending.dm
  code/HISPANIA/modules/clothing/head/jobs.dm
  code/HISPANIA/modules/clothing/under/jobs/security.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/armor.dm
  code/modules/customitems/item_defines.dm
  icons/hispania/mob/head.dmi
  icons/hispania/mob/species/grey/suit.dmi
  icons/hispania/mob/species/grey/uniform.dmi
  icons/hispania/mob/species/vox/head.dmi
  icons/hispania/mob/species/vox/suit.dmi
  icons/hispania/mob/species/vox/uniform.dmi
  icons/hispania/mob/suit.dmi
  icons/hispania/mob/uniform.dmi
  icons/hispania/obj/clothing/hats.dmi
  icons/hispania/obj/clothing/suits.dmi
  icons/hispania/obj/clothing/uniforms.dmi
  paradise.dme
Labels: Map changes, Sprites, Tweak

#601 Add Flare Box and Blackout Supply Pack
  code/HISPANIA/datums/supplypacks.dm
  code/HISPANIA/game/objects/items/weapons/storage/fancy.dm
  icons/hispania/mob/inhands/items_lefthand.dmi
  icons/hispania/mob/inhands/items_righthand.dmi
  icons/hispania/obj/food/containers.dmi
Labels: Feature, Sprites

#617 Nuevas herramientas avanzadas de cirugia [porteadas de tg]
  code/HISPANIA/game/objects/items/weapons/storage/belt.dm
  code/HISPANIA/modules/research/designs/medical_designs.dm
  code/HISPANIA/modules/surgery/tools.dm
  code/game/jobs/job/medical.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/response_team/ert_outfits.dm
  icons/hispania/obj/clothing/belts.dmi
  icons/hispania/obj/surgery.dmi
  paradise.dme
Labels: Feature, Port, Sprites, Tweak

#535 Add Whistle
  code/HISPANIA/game/objects/items/divices/whistle.dm
  code/HISPANIA/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/HISPANIA/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/HISPANIA/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/HISPANIA/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/HISPANIA/game/objects/structures/crates_lockers/security.dm
  icons/hispania/obj/tools.dmi
  paradise.dme
  sound/hispania/effects/whistle.ogg
Labels: Feature

#636 [Tweak] Los vox ni los grey pueden usar uniformes formales de capitán ni su trenchcoat, ni su hats
  code/HISPANIA/modules/clothing/head/jobs.dm
  code/HISPANIA/modules/clothing/suits/armor.dm
  code/HISPANIA/modules/clothing/under/jobs/civilian.dm
Labels: Tweak

#628 Cambios al departamento de cargo
  _maps/map_files/hispania/hispania.dmm
  code/HISPANIA/game/machinery/computer/buildandrepair.dm
  code/HISPANIA/game/machinery/computer/card.dm
  code/HISPANIA/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/__DEFINES/machines.dm
  code/game/jobs/job/support.dm
  code/game/machinery/computer/card.dm
  code/modules/mining/machine_vending.dm
  paradise.dme
Labels: Feature, Tweak

#527 [Map Change] Break Room y Ventanas Reforzadas (Lavaland)
  _maps/map_files/hispania/Lavaland.dmm
Labels: Map changes

#639 Tweak Starting Founds
  code/controllers/subsystem/jobs.dm
Labels: Tweak

#284 Anillos y guantes de boxeo al loadout.
  code/HISPANIA/modules/client/preference/loadout/loadout_gloves.dm
  code/modules/client/preference/loadout/loadout_gloves.dm
Labels: Feature, Wait
