Repository Helixis/Paradise, pull requests merged in 2020-05, with the labels that each got.

#643 SlimeCross update: Silver
  code/HISPANIA/__HELPERS/unsorted.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/baked_goods.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/other_snacks.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/sandwiches.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_oven.dm
  code/HISPANIA/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/HISPANIA/modules/research/xenobiology/crossbreeding/burning.dm
  code/HISPANIA/modules/research/xenobiology/crossbreeding/charged.dm
  code/HISPANIA/modules/research/xenobiology/crossbreeding/chilling.dm
  code/HISPANIA/modules/research/xenobiology/crossbreeding/industrial.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  icons/hispania/obj/food/food.dmi
  paradise.dme
Labels: Feature, Tweak

#654 Quirks framework + AGUESIA TRAIT/Quirk [port de tg]
  code/HISPANIA/__DEFINES/traits.dm
  code/HISPANIA/__HELPERS/cmp.dm
  code/HISPANIA/__HELPERS/unsorted.dm
  code/HISPANIA/controllers/subsystem/processing/quirks.dm
  code/HISPANIA/datums/traits/_quirk.dm
  code/HISPANIA/datums/traits/negative.dm
  code/HISPANIA/datums/traits/neutral.dm
  code/HISPANIA/modules/client/preference/preferences.dm
  code/HISPANIA/modules/mob/living/status_procs.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/subsystems.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/verbs.dm
  code/modules/client/preference/preferences.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/taste.dm
  code/modules/mob/new_player/new_player.dm
  config/example/game_options.txt
  paradise.dme
Labels: Port

#428 Colmillos vampiro con sonido
  code/game/gamemodes/vampire/vampire.dm
  sound/hispania/effects/drain_blood_new.ogg
Labels: Sound

#660 Miras para el Stun revolver y el Xray
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/stun.dm
Labels: Feature

#661 El Gordo Franses volverá a amar este PR.
  code/HISPANIA/game/objects/items/trash.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/baked_goods.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/candy.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/meat.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/misc.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/sandwiches.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_candy.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_grill.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_microwave.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_oven.dm
  code/HISPANIA/modules/food_and_drinks/recipes/tablecraft.dm
  code/HISPANIA/modules/hydroponics/grown/anonna.dm
  code/HISPANIA/modules/hydroponics/grown/cactus.dm
  code/HISPANIA/modules/hydroponics/grown/nispero.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/drinks.dm
  code/HISPANIA/modules/reagents/chemistry/recipes/drinks.dm
  code/_globalvars/lists/reagents.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  icons/hispania/obj/drinks.dmi
  icons/hispania/obj/food/candy.dmi
  icons/hispania/obj/food/food.dmi
  icons/hispania/obj/trash.dmi
  icons/obj/drinks.dmi
  paradise.dme
Labels: Feature, Fix, Sprites

#653 la Comidacion
  code/HISPANIA/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/baked_goods.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/meat.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/other_snacks.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/soups.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_microwave.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_mixer.dm
  code/HISPANIA/modules/food_and_drinks/recipes/recipes_oven.dm
  code/HISPANIA/modules/hydroponics/grown/agave.dm
  code/HISPANIA/modules/hydroponics/grown/coconut.dm
  code/HISPANIA/modules/hydroponics/grown/kiwi.dm
  code/HISPANIA/modules/hydroponics/grown/mango.dm
  code/HISPANIA/modules/hydroponics/grown/mate.dm
  code/HISPANIA/modules/hydroponics/grown/peach.dm
  code/HISPANIA/modules/hydroponics/grown/ricinus.dm
  code/HISPANIA/modules/hydroponics/grown/strawberry.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/alcohol.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/drinks.dm
  code/HISPANIA/modules/reagents/chemistry/reagents/food.dm
  code/HISPANIA/modules/reagents/chemistry/recipes/drinks.dm
  code/_globalvars/lists/reagents.dm
  code/game/machinery/vending.dm
  code/modules/hydroponics/grown/garlic.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/reagents/chemistry/reagents/food.dm
  icons/hispania/obj/drinks.dmi
  icons/hispania/obj/food/food.dmi
  icons/obj/drinks.dmi
Labels: Feature, Fix, Sprites

#662 No se puede pedir más arena en cargo
  code/datums/supplypacks.dm
Labels: Revert/Feature Removal

#582 Traducción leyes de IA
  code/datums/ai_law_sets.dm
  code/game/objects/items/weapons/AI_modules.dm
  code/modules/mob/living/silicon/ai/laws.dm
  code/modules/mob/living/silicon/laws.dm
  code/modules/mob/living/silicon/robot/laws.dm
Labels: Feature

#659 [margeen mi mierda ya] Quirks 8.0: skills departamentales, Modificaciones geneticas, Discapacidades, Implantes y Artes marciales + fix skills antagonistas +fix tools use hispano
  code/HISPANIA/datums/traits/_quirk.dm
  code/HISPANIA/datums/traits/negative.dm
  code/HISPANIA/datums/traits/neutral.dm
  code/HISPANIA/datums/traits/positive.dm
  code/HISPANIA/game/jobs/job/blueshield.dm
  code/HISPANIA/game/jobs/job/engineering.dm
  code/HISPANIA/game/jobs/job/medical.dm
  code/HISPANIA/game/jobs/job/science.dm
  code/HISPANIA/game/jobs/job/security.dm
  code/HISPANIA/game/jobs/job/supervisor.dm
  code/HISPANIA/game/jobs/job/support.dm
  code/HISPANIA/game/machinery/jukebox.dm
  code/HISPANIA/game/mecha/equipament/tools/medical_tools.dm
  code/HISPANIA/game/objects/items/miscellaneous/bell.dm
  code/HISPANIA/game/objects/items/miscellaneous/noose.dm
  code/HISPANIA/modules/client/preference/preferences.dm
  code/HISPANIA/modules/clothing/suits/armor.dm
  code/HISPANIA/modules/clothing/suits/labcoat.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/baked_goods.dm
  code/HISPANIA/modules/food_and_drinks/food/foods/meat.dm
  code/HISPANIA/modules/mob/living/status_procs.dm
  code/HISPANIA/modules/projectiles/ammo/energy.dm
  code/__HELPERS/traits.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/support.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/tools/tool_behaviour.dm
  code/modules/crafting/craft.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/projectiles/gun.dm
  code/modules/reagents/chemistry/reagents/food.dm
  code/modules/reagents/chemistry/reagents/medicine.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/spacepods/spacepod.dm
  code/modules/surgery/bones.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/limb_reattach.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/other.dm
  code/modules/surgery/surgery.dm
  paradise.dme
Labels: EL PR QUE HIZO LLORAR A SPILBERG, Feature, Fix, Tweak
