Repository Helixis/Paradise, pull requests merged in 2021-07, with the labels that each got.

#1020 Tweak Plasmacutter Damage
  code/modules/projectiles/projectile/special.dm
Labels: Balance?, Tweak

#1017 Tweak Heads no pueden ser antags.
  code/game/gamemodes/blob/blob.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/shadowling/shadowling.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/vampire/vampire.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/supervisor.dm
Labels: CAMBIO POLEMICO, Tweak

#1030 Revive el canal #baneos y log lindo para los admins en el canal privado
  code/__DEFINES/misc.dm
  code/controllers/configuration.dm
  code/modules/admin/db_ban/functions.dm
  code/modules/admin/sql_notes.dm
  code/modules/admin/stickyban.dm
  code/modules/admin/topic.dm
  config/example/config.txt
Labels: Discord

#1031 Fix baneos??? PR canal baneos dois? NOVO??
  code/controllers/configuration.dm
Labels: Discord

#1021 Fix Autosurgeon TSF Discovery
  _maps/map_files/Delta/delta_hispania.dmm
  _maps/map_files/MetaStation/MetaStation_hispania.dmm
  _maps/map_files/hispania/hispania.dmm
Labels: Fix

#1027 Port Big Chungus (Colonial Marines)
  code/hispania/game/machinery/vending.dm
  code/hispania/modules/clothing/head/helmets.dm
  code/hispania/modules/clothing/suits/miscellaneous.dm
  icons/hispania/mob/head.dmi
  icons/hispania/mob/suit.dmi
  icons/hispania/obj/clothing/hats.dmi
  icons/hispania/obj/clothing/suits.dmi
Labels: Port

#1036 Canal OOC en discord - NO mergear aun
  code/__DEFINES/misc.dm
  code/controllers/configuration.dm
  code/controllers/subsystem/discord.dm
  code/game/verbs/ooc.dm
  config/example/config.txt
Labels: DO NOT MERGE, Discord

#1032 Port CIV 13 Fullscreen
  code/hispania/controllers/fullscreen.dm
  code/modules/client/client_defines.dm
  paradise.dme
Labels: Port

#1045 The Brig Brother Its Watching you
  code/hispania/game/objects/items/weapons/cards_ids.dm
  paradise.dme
Labels: Administración

#1047 Arregla la skin invisible del Cyborg Janitor
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Fix
