Repository Helixis/Paradise, pull requests merged in 2021-03, with the labels that each got.

#812 Jackboots BUFF
  code/modules/clothing/shoes/miscellaneous.dm
  sound/hispania/effects/jackboot1.ogg
  sound/hispania/effects/jackboot2.ogg
Labels: Fix

#813 Fix 7 sprites de pildoras de HISPANIA
  code/modules/reagents/chemistry/machinery/chem_master.dm
Labels: Fix, Sprites

#816 Fix hispania.z6.dmm
  _maps/map_files/hispania/z6.dmm
Labels: Fix, Map changes

#820 Update 14/03/2021
  .github/workflows/ci.yml
  code/__HELPERS/traits.dm
  code/_globalvars/traits.dm
  code/_onclick/item_attack.dm
  code/datums/spells/shapeshift.dm
  code/game/gamemodes/wizard/spellbook.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/hand_item.dm
  code/game/objects/items/weapons/extinguisher.dm
  code/game/objects/items/weapons/pneumaticCannon.dm
  code/game/objects/items/weapons/signs.dm
  code/hispania/modules/crafting/recipes.dm
  code/hispania/modules/crafting/tailoring.dm
  code/hispania/modules/food_and_drinks/recipes/tablecraft.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/crafting/craft.dm
  code/modules/crafting/recipes.dm
  code/modules/crafting/tailoring.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_table.dm
  code/modules/hydroponics/fermenting_barrel.dm
  code/modules/instruments/objs/items/instruments.dm
  code/modules/martial_arts/combos/krav_maga/leg_sweep.dm
  code/modules/martial_arts/combos/krav_maga/lung_punch.dm
  code/modules/martial_arts/combos/krav_maga/neck_chop.dm
  code/modules/martial_arts/krav_maga.dm
  code/modules/martial_arts/martial.dm
  code/modules/mining/lavaland/ash_flora.dm
  code/modules/mining/lavaland/loot/ashdragon_loot.dm
  code/modules/mining/lavaland/loot/tendril_loot.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/power/lighting.dm
  code/modules/projectiles/gun.dm
  code/modules/surgery/organs/vocal_cords.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/crafting_lists.dm
  icons/obj/vending.dmi
  paradise.dme
  sound/effects/kiss.ogg
  sound/effects/tableslam.ogg
  sound/weapons/slap.ogg
  tools/ci/dbconfig.txt
  tools/ci/generate_sql_scripts.py
Labels: Actualizacion de PARADISE

#818 Intento de reparar el CI compile maps
  _maps/delta.dm
  _maps/hispania_dumpster/Delta/delta.dmm
  _maps/hispania_dumpster/desktop.ini
  _maps/map_files/Delta/z2.dmm
Labels: Fix

#822 En Hispania los PRs te cierran a ti.
  code/game/machinery/doors/airlock.dm
  code/game/objects/structures/door_assembly.dm
  icons/hispania/obj/doors/overlays.dmi
Labels: Sprites, Tweak

#825 Resaltar items por los que pases por encima en la UI
  code/game/objects/items.dm
  code/hispania/game/objects/items.dm
  code/modules/client/preference/preferences.dm
  paradise.dme
Labels: Feature, Port

#828 Cyborborgs buff, mas Menús RADIALES UNA VEZ MAS
  code/modules/mob/living/silicon/robot/robot.dm
  icons/hispania/mob/robots.dmi
Labels: Tweak

#831 Gps fix
  code/modules/telesci/gps.dm
Labels: Fix

#827 Full-automatic firemode // Arma nueva para el uplink
  _maps/map_files/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/map_files/RandomZLevels/evil_santa.dmm
  _maps/map_files/RandomZLevels/spacebattle.dmm
  _maps/map_files/generic/centcomm.dmm
  _maps/map_files/hispania/hispania.dmm
  _maps/map_files/hispania/z2.dmm
  code/_onclick/click.dm
  code/datums/outfits/outfit_admin.dm
  code/datums/supplypacks.dm
  code/datums/uplink_item.dm
  code/game/gamemodes/wizard/rightandwrong.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/effects/spawners/random_spawners.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/structures/crates_lockers/closets/syndicate.dm
  code/hispania/datums/autofiresystem.dm
  code/hispania/datums/uplink_item.dm
  code/hispania/game/objects/items.dm
  code/hispania/modules/projectiles/ammunition/magazines.dm
  code/hispania/modules/projectiles/guns/fullauto.dm
  code/hispania/modules/projectiles/guns/projectile/natasha.dm
  code/modules/admin/verbs/striketeam_syndicate.dm
  code/modules/antagonists/traitor/contractor/items/contractor_kit.dm
  code/modules/awaymissions/mission_code/stationCollision.dm
  code/modules/client/client_defines.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/saw.dm
  code/modules/projectiles/guns/projectile/toy.dm
  code/modules/projectiles/projectile.dm
  code/modules/station_goals/bluespace_tap.dm
  icons/hispania/mob/inhands/guns_lefthand.dmi
  icons/hispania/mob/inhands/guns_righthand.dmi
  icons/hispania/obj/ammo.dmi
  icons/hispania/obj/guns/projectile.dmi
  icons/hispania/obj/projectiles.dmi
  icons/mob/inhands/guns_righthand.dmi
  paradise.dme
Labels: Feature, Map changes, Port, Sprites, Tweak

#823 Funcionamiento original de la duct tape
  code/datums/components/ducttape.dm
Labels: Tweak

#832 Discord Embed New Round
  code/game/gamemodes/game_mode.dm
  code/hispania/datums/discord.dm
  paradise.dme
Labels: Discord

#834 Full Automatic Firemode Fix
  code/hispania/datums/autofiresystem.dm
Labels: Fix

#836 Maint drones pueden volver a entender el lenguaje universal
  code/modules/mob/living/silicon/robot/drone/drone.dm
Labels: Tweak
