Repository Helixis/Paradise, pull requests merged in 2021-06, with the labels that each got.

#955 Medbay Oxigen Assistant: 358/2 days (funky mode edition) DX EDITION 2021 FINAL TAKE: LAST RESORT
  code/__DEFINES/combat.dm
  code/datums/diseases/_disease.dm
  code/hispania/modules/reagents/chemistry/reagents/medicine.dm
  code/hispania/modules/reagents/reagent_containers/moa.dm
  code/hispania/modules/research/designs/medical_designs.dm
  code/modules/mob/living/damage_procs.dm
  icons/hispania/mob/inhands/items_lefthand.dmi
  icons/hispania/mob/inhands/items_righthand.dmi
  icons/hispania/obj/moa.dmi
  paradise.dme
  sound/hispania/machines/moa.ogg
Labels: Feature, Sprites

#970 [Naga] Tormentas de Nieve / Balance de Mobs / Slippery Ice
  _maps/base_map.dm
  _maps/map_files/hispania/_MAP_DEFINES.dm
  _maps/map_files/hispania/z4.dmm
  code/hispania/datums/weather/weather_types/naga_storm.dm
  code/hispania/game/turf/hispania_floor.dm
  code/hispania/modules/mob/living/simple_animal/hostile/netherworld.dm
  code/modules/mob/living/simple_animal/hostile/netherworld.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  icons/effects/weather_effects.dmi
  paradise.dme
Labels: Feature

#971 bottom text
  code/modules/mob/living/say.dm
Labels: DO NOT MERGE, EL PR QUE HIZO LLORAR A SPILBERG

#975 Fix Map Rotation
  code/controllers/configuration.dm
  code/modules/shuttle/emergency.dm
Labels: Fix

#977 Tweak Skin.dmf
  interface/skin.dmf
Labels: CAMBIO POLEMICO, Tweak

#979 Tweak Mega Carp Random Values
  code/modules/mob/living/simple_animal/hostile/carp.dm
Labels: Tweak

#981 La cajita del minero ya incluye la crowbar >:(
  code/hispania/game/objects/items/weapons/storage/boxes.dm
Labels: Fix

#974 Add SpacePods Models (Heavy, Light, Estandar)
  code/hispania/modules/research/designs/spacepod_designs.dm
  code/hispania/modules/spacepods/equipment.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/spacepods/spacepod.dm
Labels: Feature

#982 [Map Changes] Hispania Disposals
  _maps/map_files/hispania/hispania.dmm
Labels: Héroe de Hispania, Map changes

#978 New York Update
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/firealarm.dm
  code/game/machinery/lightswitch.dm
  code/game/machinery/requests_console.dm
  code/game/machinery/status_display.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/mountable_frames/newscaster_frame.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/newscaster/obj/newscaster.dm
  code/modules/power/apc.dm
  code/modules/security_levels/security_levels.dm
  icons/hispania/obj/computer.dmi
  icons/hispania/obj/monitors.dmi
  icons/hispania/obj/power.dmi
  icons/hispania/obj/radio.dmi
  icons/hispania/obj/status_display.dmi
  icons/hispania/obj/terminals.dmi
  icons/obj/monitors.dmi
Labels: Feature, Sprites, Tweak

#972 Balance Armadura
  code/hispania/modules/research/xenobiology/crossbreeding/_clothing.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Balance

#973 [Map Changes] Reparaciones Delta y Meta
  _maps/map_files/Delta/delta_hispania.dmm
  _maps/map_files/MetaStation/MetaStation_hispania.dmm
Labels: Map changes

#985 Tweak Status Bar
  code/hispania/game/atoms.dm
  code/hispania/modules/status_bar/status_bar.dm
  interface/skin.dmf
  paradise.dme
Labels: Héroe de Hispania, Tweak

#989 Fix Radio Sprites
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/radio/radio.dm
Labels: Fix

#988 Tweak HECK Block Hair
  code/modules/mining/equipment/explorer_gear.dm
Labels: Tweak

#986 Más comida
  code/hispania/game/objects/items/weapons/manuals.dm
  code/hispania/modules/food_and_drinks/food/foods/ingredients.dm
  code/hispania/modules/food_and_drinks/food/foods/meat.dm
  code/hispania/modules/food_and_drinks/food/foods/sandwiches.dm
  code/hispania/modules/food_and_drinks/recipes/recipes_mixer.dm
  code/hispania/modules/food_and_drinks/recipes/recipes_oven.dm
  code/hispania/modules/food_and_drinks/recipes/tablecraft.dm
  code/hispania/modules/reagents/chemistry/reagents/food.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  icons/hispania/obj/food/food.dmi
Labels: nom nom nom

#987 Add Stamp Sounds
  code/modules/paperwork/paper.dm
  code/modules/paperwork/stamps.dm
  sound/hispania/effects/stamp.ogg
  sound/hispania/effects/stamp_suicide.ogg
Labels: Futuro de Hispania, Héroe de Hispania, Priority, Tweak

#990 Termina las SpacePods
  code/hispania/__DEFINES/pod.dm
  code/hispania/modules/research/designs/spacepod_designs.dm
  code/hispania/modules/spacepods/equipment.dm
  code/hispania/modules/spacepods/spacepod.dm
  code/modules/customitems/item_defines.dm
  code/modules/research/designs/spacepod_designs.dm
  code/modules/spacepods/equipment.dm
  code/modules/spacepods/spacepod.dm
  icons/hispania/goonstation/48x48/pods.dmi
  icons/hispania/obj/spacepod.dmi
  paradise.dme
Labels: Sprites, Tweak

#991 No destruiran lo que he hecho, papeles.
  _maps/map_files/hispania/hispania.dmm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/message.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/firealarm.dm
  code/modules/atmospherics/machinery/airalarm.dm
Labels: Fix, Tweak

#992 Balance Event Manager
  code/modules/events/event_container.dm
Labels: Balance

#980 offset fix
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
Labels: Fix

#976 Actualiza el precio del build your own KA
  code/modules/mining/machine_vending.dm
Labels: Balance, Tweak

#993 Add Ntade Skins para Cyborgs
  code/modules/mob/living/silicon/robot/robot.dm
  icons/hispania/mob/robots.dmi
  icons/mob/custom_synthetic/custom-synthetic.dmi
Labels: Sprites

#996 Tweak Dead Vote
  code/controllers/subsystem/vote.dm
Labels: Tweak

#1000 PR 1000 - DABABY MEJORADO LESGOOO
  _maps/map_files/dababy/sexo.dmm
Labels: Map changes

#995 Tweak Masivo a los Goliaths Domesticados
  code/__DEFINES/goliath.dm
  code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
Labels: Tweak

#1001 Update 10/06/2021
  code/controllers/configuration.dm
  code/datums/outfits/outfit_admin.dm
  code/game/data_huds.dm
  code/game/gamemodes/cult/runes.dm
  code/game/gamemodes/miniantags/guardian/types/healer.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/wizard/soulstone.dm
  code/game/machinery/computer/robot.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/turfs/simulated/floor/light_floor.dm
  code/game/turfs/turf.dm
  code/modules/mining/lavaland/loot/colossus_loot.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/mob_helpers.dm
  code/modules/reagents/chemistry/reagents/medicine.dm
  code/modules/reagents/chemistry/reagents/water.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/telesci/gps.dm
  icons/obj/stationobjs.dmi
  tools/mapmerge2/requirements.txt
Labels: Actualizacion de PARADISE

#1002 Tweak Quirks a la DB
  code/modules/client/preference/preferences_mysql.dm
Labels: Tweak

#1003 Tweak Emote CD
  code/modules/mob/living/carbon/human/emote.dm
Labels: Tweak

#998 [Naga] Fix Doors, Tweak Localizaciones.
  _maps/map_files/hispania/z4.dmm
  code/hispania/game/objects/structures/mineral_doors.dm
  code/hispania/modules/mob/living/simple_animal/hostile/megafauna/wendigo.dm
  icons/hispania/mob/animals.dmi
  icons/hispania/mob/lavaland/meatoverlord.dmi
  icons/hispania/mob/lavaland/wendigo.dmi
  icons/hispania/obj/doors.dmi
  icons/hispania/obj/lavaland/artefacts.dmi
  icons/hispania/obj/projectiles.dmi
  paradise.dme
  sound/hispania/effects/gravhit.ogg
Labels: Map changes, Tweak

#1004 Tweak Multiplicador de curación al dormir con pijama.
  code/modules/mob/living/carbon/life.dm
Labels: Tweak

#997 Le Cloaker Mask Update
  .vscode/settings.json
  code/hispania/datums/supplypacks.dm
  code/hispania/modules/clothing/mask/gasmask.dm
  code/hispania/modules/clothing/mask/miscellaneous.dm
  icons/hispania/mob/mask.dmi
  icons/hispania/mob/species/drask/mask.dmi
  icons/hispania/mob/species/grey/mask.dmi
  icons/hispania/mob/species/tajaran/mask.dmi
  icons/hispania/mob/species/unathi/mask.dmi
  icons/hispania/mob/species/vox/mask.dmi
  icons/hispania/obj/clothing/masks.dmi
  paradise.dme
  sound/hispania/voice/hailer/cloaker/beated.ogg
  sound/hispania/voice/hailer/cloaker/beep.ogg
  sound/hispania/voice/hailer/cloaker/celilitis.ogg
  sound/hispania/voice/hailer/cloaker/corners.ogg
  sound/hispania/voice/hailer/cloaker/cry.ogg
  sound/hispania/voice/hailer/cloaker/difficulty-tweak.ogg
  sound/hispania/voice/hailer/cloaker/expected.ogg
  sound/hispania/voice/hailer/cloaker/forums.ogg
  sound/hispania/voice/hailer/cloaker/hitting-yourself.ogg
  sound/hispania/voice/hailer/cloaker/im_late.ogg
  sound/hispania/voice/hailer/cloaker/meeting.ogg
  sound/hispania/voice/hailer/cloaker/missed.ogg
  sound/hispania/voice/hailer/cloaker/no-return.ogg
  sound/hispania/voice/hailer/cloaker/not-tough.ogg
  sound/hispania/voice/hailer/cloaker/pants.ogg
  sound/hispania/voice/hailer/cloaker/resisting.ogg
  sound/hispania/voice/hailer/cloaker/s-word.ogg
  sound/hispania/voice/hailer/cloaker/speak-up.ogg
  sound/hispania/voice/hailer/cloaker/wish-true.ogg
  sound/hispania/voice/hailer/cloaker/work-smarter.ogg
Labels: Sound, Sprites

#1005 Tweak Hand Held Body Scanner
  code/hispania/modules/research/designs/medical_designs.dm
Labels: Tweak

#1006 Fix Attacklog
  code/hispania/modules/mob/living/simple_animal/hostile/megafauna/wendigo.dm
Labels: Fix

#1012 Add Pogfish Paperwork
  code/__HELPERS/text.dm
  code/modules/client/asset_cache.dm
  icons/hispania/paper_icons/pogfish.png
Labels: Sprites

#1007 Add Gashapon Arcade
  _maps/map_files/Delta/delta_hispania.dmm
  _maps/map_files/MetaStation/MetaStation_hispania.dmm
  _maps/map_files/hispania/hispania.dmm
  code/hispania/game/machinery/gashapon.dm
  icons/hispania/obj/arcade.dmi
  paradise.dme
Labels: Feature, Sprites

#1008 Tweak Baked Goods
  code/hispania/modules/food_and_drinks/food/foods/baked_goods.dm
  code/hispania/modules/food_and_drinks/recipes/recipes_oven.dm
Labels: Tweak

#1010 Port Vaporwave UI (Goon)
  code/__HELPERS/type2type.dm
  code/modules/client/preference/preferences.dm
  code/modules/client/preference/preferences_mysql.dm
  icons/hispania/mob/screen_vaporwave.dmi
Labels: Port

#1013 Add Pekora Hair
  code/hispania/modules/mob/new_player/sprite_accessories/human/human_hair.dm
  icons/hispania/mob/sprite_accessories/human/human_hair.dmi
Labels: Sprites

#1014 Fix Loadout Retro Suits
  code/hispania/modules/client/preference/loadout/loadout_uniform.dm
Labels: Fix

#1022 Update 27/06/2021
  _maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm
  _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
  _maps/map_files/RandomZLevels/blackmarketpackers.dmm
  _maps/map_files/RandomZLevels/centcomAway.dmm
  _maps/map_files/RandomZLevels/moonoutpost19.dmm
  _maps/map_files/RandomZLevels/terrorspiders.dmm
  _maps/map_files/RandomZLevels/undergroundoutpost45.dmm
  code/datums/datacore.dm
  code/datums/uplink_item.dm
  code/game/dna/mutations/powers.dm
  code/game/gamemodes/cult/cult_structures.dm
  code/game/gamemodes/miniantags/bot_swarm/swarmer.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/vampire/vampire_powers.dm
  code/game/gamemodes/wizard/soulstone.dm
  code/game/machinery/pipe/construction.dm
  code/game/objects/items/devices/radio/beacon.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/tools/tool_behaviour.dm
  code/game/objects/items/tools/welder.dm
  code/game/objects/items/weapons/cigs.dm
  code/game/objects/items/weapons/rpd.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/loom.dm
  code/game/objects/structures/watercloset.dm
  code/modules/antagonists/traitor/contractor/datums/syndicate_contract.dm
  code/modules/customitems/item_defines.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/reagents/reagent_containers/patch.dm
  code/modules/ruins/lavalandruin_code/puzzle.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/tgui/modules/generic_crew_manifest.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/species/vox/gloves.dmi
  paradise.dme
  tgui/packages/tgui/index.js
  tgui/packages/tgui/interfaces/GenericCrewManifest.js
  tgui/packages/tgui/public/tgui.bundle.css
  tgui/packages/tgui/public/tgui.bundle.js
  tgui/packages/tgui/styles/themes/nologo.scss
Labels: Actualizacion de PARADISE

#1023 Add 4 Hologramas Nuevos IA
  code/modules/mob/living/silicon/ai/ai.dm
  icons/hispania/mob/ai.dmi
Labels: Sprites

#1018 Port Barcardine (Colonial Marines)
  code/hispania/game/machinery/vending.dm
  code/hispania/game/objects/items/trash.dm
  code/hispania/modules/food_and_drinks/food/foods/candy.dm
  icons/hispania/obj/food/candy.dmi
  icons/hispania/obj/trash.dmi
Labels: Port

#1011 Add Phazon Purple Paintkit by killer7luis
  code/hispania/game/mecha/paintkits.dm
  code/hispania/modules/research/designs/mechfabricator_designs.dm
  icons/hispania/mecha/mecha.dmi
Labels: Sprites

#1016 Add Dientes de Tiburón (BearTrap Handmade)
  code/hispania/game/objects/items/weapons/legcuffs.dm
  code/hispania/modules/crafting/recipes.dm
  icons/hispania/obj/items.dmi
  paradise.dme
Labels: Feature
