Repository Helixis/Paradise, pull requests merged in 2021-09, with the labels that each got.

#1062 No mas giga rads
  code/datums/radiation_wave.dm
Labels: Priority, Catástrofe Racial

#1019 Port Welderpack (Colonial Marines)
  code/hispania/game/objects/items/weapons/storage/backpack.dm
  code/hispania/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  icons/hispania/mob/back.dmi
  icons/hispania/mob/inhands/clothing_lefthand.dmi
  icons/hispania/mob/inhands/clothing_righthand.dmi
  icons/hispania/obj/storage/storage.dmi
  paradise.dme
Labels: Port

#1056 Energy Sword Deflect
  code/game/objects/items/weapons/melee/energy.dm
  code/hispania/game/objects/items/weapons/melee/energy.dm
  code/hispania/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  icons/hispania/obj/swords.dmi
  paradise.dme
  sound/hispania/weapons/light_reflect.ogg
Labels: Feature

#1055 Blue Flame Refactor / Martial Art Block Visual Feedback
  code/hispania/modules/martial_arts/bscqc.dm
  code/modules/martial_arts/martial.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Tweak, Refactor
