Repository Helixis/Paradise, pull requests merged in 2021-05, with the labels that each got.

#869 Fix Sprite Pills
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/pill.dm
  icons/hispania/obj/chemical.dmi
Labels: Fix

#872 monos hiper agresivos cuando los arrastras no more
  code/hispania/modules/mob/living/carbon/human/species/monkey_combat.dm
Labels: Balance

#876 Tweak Jackboot Sound
  code/hispania/modules/clothing/shoes/miscellaneous.dm
  paradise.dme
Labels: Tweak

#878 Bar de CC by SmolKot
  _maps/map_files/hispania/z2.dmm
  code/hispania/game/area/Space Station 13 areas.dm
Labels: Map changes

#875 Add Port Laugh and Screams TG
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species/_species.dm
  code/modules/mob/living/carbon/human/species/abductor.dm
  code/modules/mob/living/carbon/human/species/diona.dm
  code/modules/mob/living/carbon/human/species/drask.dm
  code/modules/mob/living/carbon/human/species/machine.dm
  code/modules/mob/living/carbon/human/species/monkey.dm
  code/modules/mob/living/carbon/human/species/vox.dm
  sound/hispania/voice/human/femalescream_1.ogg
  sound/hispania/voice/human/femalescream_2.ogg
  sound/hispania/voice/human/femalescream_3.ogg
  sound/hispania/voice/human/femalescream_4.ogg
  sound/hispania/voice/human/femalescream_5.ogg
  sound/hispania/voice/human/malescream_1.ogg
  sound/hispania/voice/human/malescream_2.ogg
  sound/hispania/voice/human/malescream_3.ogg
  sound/hispania/voice/human/malescream_4.ogg
  sound/hispania/voice/human/malescream_5.ogg
  sound/hispania/voice/human/manlaugh.ogg
  sound/hispania/voice/human/silence.ogg
  sound/hispania/voice/human/womanlaugh.ogg
Labels: Sound

#877 Tweak Holy Water
  code/modules/reagents/chemistry/reagents/water.dm
Labels: Tweak

#879 Fix Cigarrillos con Welder
  code/game/objects/items/weapons/cigs.dm
Labels: Fix

#870 Add Pistas de Audio (Ambiente)
  code/__DEFINES/sound.dm
  sound/hispania/ambience/ambidanger3.ogg
  sound/hispania/ambience/ambigen16.ogg
  sound/hispania/ambience/ambiruin8.ogg
  sound/hispania/ambience/ambispace3.ogg
  sound/hispania/ambience/ambispace4.ogg
Labels: Sound

#874 Tweak Dropper and Syringe Dump
  code/hispania/modules/reagents/reagent_containers/dropper.dm
  code/hispania/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagent_containers/syringes.dm
  paradise.dme
Labels: Feature

#866 Add Cataplasmas Herbales (Lavaland)
  code/hispania/game/objects/items/divices/stacks/medical.dm
  code/hispania/modules/crafting/recipes.dm
  icons/hispania/obj/miscellaneous.dmi
Labels: Feature

#851 La Gran Ingeniería Update (Terminada)
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes

#871 [Map Change] Reparaciones menores al mapa y añadido al janitor.
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes

#881 Engicart Rods
  code/game/objects/structures/engicart.dm
  icons/obj/engicart.dmi
Labels: Sprites, Tweak

#880 L6 SAW TOY BUFF
  code/modules/projectiles/ammunition/magazines.dm
Labels: Tweak

#885 Cinta policial y de ingeniería COMEBACK
  code/hispania/game/objects/items/policetape.dm
  code/hispania/game/objects/structures/crates_lockers/closets/secure/security.dm
  icons/hispania/effects/hazard_tape.dmi
  icons/hispania/obj/policetape.dmi
Labels: Fix, Tweak

#887 Tweak Orion Trail Prize
  code/game/machinery/computer/arcade.dm
Labels: Balance

#787 Hoy termino mis platforms
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/hispania/game/objects/structures/platform.dm
  icons/hispania/obj/platform.dmi
  paradise.dme
Labels: Feature, Sprites

#886 Retoques New Inge
  _maps/map_files/hispania/hispania.dmm
  code/hispania/game/area/Space Station 13 areas.dm
Labels: Map changes

#892 Fix Caviar Sprite
  code/hispania/game/objects/items/trash.dm
Labels: Fix

#890 Fix Cataplasmas
  code/hispania/game/objects/items/divices/stacks/medical.dm
  code/hispania/modules/crafting/recipes.dm
Labels: Fix

#894 Fix Arepa Ghost Sprite
  icons/hispania/obj/food/food.dmi
Labels: Fix

#895 Add Port /VG/ Posters
  code/game/objects/effects/decals/contraband.dm
  code/hispania/game/objects/effects/spawners/decals/contraband.dm
  icons/hispania/obj/contraband.dmi
  paradise.dme
Labels: Sprites

#898 Tweak Readys en Lobby
  code/modules/mob/new_player/new_player.dm
Labels: Feature, Futuro de Hispania

#899 Tweak ManLaugh OGG
  sound/hispania/voice/human/manlaugh.ogg
Labels: Sound, Tweak

#882 VUELVE EL OLD MAN EN SU GLORIA
  code/hispania/game/gamemodes/miniantags/oldman/oldman.dm
  code/hispania/game/gamemodes/miniantags/oldman/pocket_dimension.dm
  code/hispania/game/objects/structures/femur_breaker.dm
  code/hispania/modules/events/oldman.dm
  icons/hispania/mob/oldman.dmi
  sound/hispania/effects/oldman/sacrifice.ogg
Labels: Balance, Feature, Fix

#891 Add Libro de las Arepas y Teleciencias
  _maps/map_files/hispania/hispania.dmm
  code/hispania/game/objects/items/weapons/manuals.dm
Labels: Feature, Futuro de Hispania

#889 Pequeño rework al Ariete + Humo al romperse airlocks
  code/game/machinery/doors/airlock.dm
  code/hispania/game/objects/items/weapons/melee/misc.dm
  icons/hispania/mob/inhands/items_lefthand.dmi
  icons/hispania/mob/inhands/items_righthand.dmi
  icons/hispania/obj/items.dmi
  icons/mob/otherHuman/human.dmi
Labels: Sprites, Tweak

#888 Add Mimenomoly Event
  code/hispania/modules/events/tear_of_silence.dm
  code/hispania/modules/mob/living/simple_animal/hostile/retaliate/mime.dm
  code/modules/events/event_container.dm
  icons/hispania/mob/animals.dmi
  paradise.dme
Labels: Feature

#896 Add Lona and Cocoana Plushies
  code/hispania/game/objects/items/toys/plushies.dm
  code/hispania/modules/client/preference/loadout/loadout_general.dm
  icons/hispania/obj/toy.dmi
  paradise.dme
  sound/hispania/effects/toys/cocoana1.ogg
  sound/hispania/effects/toys/cocoana2.ogg
  sound/hispania/effects/toys/cocoana3.ogg
  sound/hispania/effects/toys/cocoana4.ogg
  sound/hispania/effects/toys/lona1.ogg
  sound/hispania/effects/toys/lona2.ogg
  sound/hispania/effects/toys/yeah.ogg
Labels: Sound, Sprites

#901 New Lobby Music
  code/controllers/subsystem/ticker.dm
  sound/music/title13.ogg
  sound/serversound_list.txt
Labels: Sound

#900 Add Pene Waffle
  code/hispania/modules/food_and_drinks/food/foods/baked_goods.dm
  code/hispania/modules/food_and_drinks/recipes/recipes_oven.dm
  icons/hispania/obj/food/food.dmi
Labels: Futuro de Hispania, Sprites

#893 Add Plazmite Lamp and Plazmite Cartilage
  code/game/objects/items/weapons/storage/bags.dm
  code/hispania/game/objects/items/miscellaneous/plazmite_stuff.dm
  code/hispania/game/objects/items/stacks/sheets/leather.dm
  code/hispania/modules/crafting/recipes.dm
  code/hispania/modules/food_and_drinks/food/foods/meat.dm
  code/hispania/modules/mob/living/simple_animal/hostile/mining/plazmite.dm
  icons/hispania/obj/lavaland/artefacts.dmi
  paradise.dme
Labels: Feature, Sprites

#907 Fix: Legion Cores
  code/modules/mining/equipment/regenerative_core.dm
Labels: Balance, Fix

#911 Tweak Fauna de Maint
  _maps/map_files/hispania/hispania.dmm
  code/hispania/game/objects/effects/spawners/lootdrop.dm
Labels: Catástrofe Racial, Feature

#914 Bugfix: Arreglo del casco antibalas
  code/modules/clothing/head/helmet.dm
  icons/hispania/mob/head.dmi
Labels: Fix

#909 Llega el ERP a la estacion Hispania
  code/hispania/datums/supplypacks.dm
  code/hispania/game/machinery/vending.dm
  code/hispania/game/objects/items/weapons/storage/erp.dm
  code/hispania/game/objects/items/weapons/storage/fancy.dm
  code/hispania/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/hispania/modules/client/preference/loadout/loadout_general.dm
  code/hispania/modules/food_and_drinks/food/foods/candy.dm
  code/modules/mining/equipment/survival_pod.dm
  icons/hispania/mob/inhands/items_lefthand.dmi
  icons/hispania/mob/inhands/items_righthand.dmi
  icons/hispania/obj/food/candy.dmi
  icons/hispania/obj/food/containers.dmi
  icons/hispania/obj/items.dmi
  paradise.dme
Labels: Feature, Port, Priority, Sprites

#915 Retoques al maint fauna
  code/hispania/game/objects/effects/spawners/lootdrop.dm
  code/modules/mob/living/simple_animal/friendly/snake.dm
Labels: Catástrofe Racial, Tweak

#913 Add Port Pinturas /vg/
  _maps/map_files/hispania/hispania.dmm
  code/hispania/game/objects/structures/signs.dm
  icons/hispania/obj/decals.dmi
  paradise.dme
Labels: Map changes, Port, Sprites

#903 Bar CC: MiniMed y Jardín
  _maps/map_files/hispania/z2.dmm
Labels: Map changes

#917 Tweaks y Fixes varios
  code/game/objects/items/weapons/storage/bags.dm
  code/hispania/game/objects/items/weapons/melee/misc.dm
  code/hispania/modules/events/oldman.dm
  code/hispania/modules/hydroponics/grown/money.dm
  code/hispania/modules/mining/equipment/kinetic_crusher.dm
  code/hispania/modules/mob/living/simple_animal/kiwi.dm
  code/modules/projectiles/guns/energy/nuclear.dm
Labels: Fix, Tweak

#919 Fix NanoMap Hispania
  code/modules/client/asset_cache.dm
  icons/_nanomaps/Hispania_nanomap_z1.png
Labels: EL PR QUE HIZO LLORAR A SPILBERG, Fix

#918 monkey fix
  code/hispania/modules/mob/living/carbon/human/species/monkey_combat.dm
Labels: Fix

#921 Tweak Mining Belts
  code/hispania/modules/crafting/recipes.dm
Labels: Feature, Tweak

#905 Tweak Curas Avanzadas Virus
  code/datums/diseases/advance/advance.dm
Labels: Balance, Feature

#922 Add Suspicious Flash Paintkit
  code/hispania/game/machinery/vending.dm
  code/hispania/game/objects/items/miscellaneous/paintkits_items.dm
  icons/hispania/obj/miscellaneous.dmi
  paradise.dme
  sound/hispania/effects/mongos.ogg
Labels: DO NOT MERGE, EL PR QUE HIZO LLORAR A SPILBERG

#916 Add Port Salmon Recipes /VG/
  _maps/map_files/hispania/hispania.dmm
  code/hispania/game/objects/items/weapons/manuals.dm
  code/hispania/modules/food_and_drinks/food/foods/meat.dm
  code/hispania/modules/food_and_drinks/food/foods/soups.dm
  code/hispania/modules/food_and_drinks/recipes/recipes_grill.dm
  code/hispania/modules/food_and_drinks/recipes/recipes_microwave.dm
  icons/hispania/obj/food/food.dmi
Labels: Port, Sprites

#920 FIx inducers runtimes
  code/hispania/game/objects/items/inducer.dm
  code/hispania/modules/power/cell.dm
  code/modules/power/cell.dm
Labels: Fix, Refactor

#928 [Map Changes] Rechargers a Blueshield e Ingenieria
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes

#930 Tweak Populatecontent instead of New
  code/hispania/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/hispania/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/hispania/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/hispania/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/hispania/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Tweak

#908 Add Quickclot Kit Surgical/Survival (IB Stopper)
  code/game/jobs/job/support.dm
  code/hispania/datums/supplypacks.dm
  code/hispania/game/objects/items/divices/stacks/medical.dm
  code/hispania/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/hispania/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/mining/machine_vending.dm
  icons/hispania/obj/miscellaneous.dmi
Labels: Feature, Sprites

#929 Platform Arreglada
  code/hispania/game/objects/structures/platform.dm
Labels: Fix

#931 Fix Sprite Drinks Hispania
  code/hispania/game/machinery/vending.dm
  code/hispania/modules/food_and_drinks/drinks/drinks/cans.dm
Labels: Fix

#933 Tweak Space Pod Mining Kit
  code/modules/mining/machine_vending.dm
Labels: Tweak

#934 Update 20/05/2021
  code/datums/outfits/outfit_admin.dm
  code/game/machinery/adv_med.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/client/preference/preferences.dm
  code/modules/economy/ATM.dm
  code/modules/events/apc_short.dm
  icons/mob/inhands/64x64_guns_lefthand.dmi
  icons/mob/inhands/64x64_guns_righthand.dmi
  icons/obj/clothing/hats.dmi
Labels: Actualizacion de PARADISE

#938 Tweak Noose
  code/hispania/game/objects/items/miscellaneous/noose.dm
Labels: Tweak

#936 Add Port Fitness Vending Bay
  _maps/map_files/hispania/hispania.dmm
  code/hispania/game/machinery/vending.dm
  code/hispania/modules/food_and_drinks/drinks/drinks/drinks.dm
  icons/hispania/obj/drinks.dmi
  icons/hispania/obj/vending.dmi
  paradise.dme
Labels: Feature, Port

#939 Tweak Medikits Vending Lavaland
  code/modules/mining/machine_vending.dm
Labels: Tweak

#937 Tweak Random Tips
  strings/tips.txt
Labels: Tweak

#940 (Clothes) Ropas de Acolito para la religion de Lady Elzra
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  code/hispania/modules/clothing/under/jobs/civilian.dm
  icons/hispania/mob/uniform.dmi
  icons/hispania/obj/clothing/uniforms.dmi
Labels: Sprites

#926 Add Port Drips and Airpods /TG/
  code/hispania/game/machinery/vending.dm
  code/hispania/modules/clothing/shoes/miscellaneous.dm
  code/hispania/modules/instruments/obj/items/headphones.dm
  icons/hispania/mob/ears.dmi
  icons/hispania/mob/feet.dmi
  icons/hispania/obj/clothing/shoes.dmi
  icons/hispania/obj/items.dmi
  paradise.dme
Labels: Feature

#941 WORK HARDER NOT SMARTER
  _maps/map_files/hispania/hispania.dmm
  code/hispania/game/machinery/jukebox.dm
  icons/hispania/obj/hispaniabox.dmi
  sound/hispania/hispaniabox/harder.ogg
Labels: Feature, Map changes, Tweak

#946 Fix Sprite Sniper Compacto
  icons/hispania/obj/guns/projectile.dmi
Labels: Fix

#943 (Clothes) Paga dia nitroso 2
  code/hispania/game/machinery/vending.dm
  code/hispania/modules/clothing/mask/miscellaneous.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/hispania/mob/mask.dmi
  icons/hispania/obj/clothing/masks.dmi
  paradise.dme
Labels: Sprites

#947 Fix Salmon Book
  code/hispania/game/objects/items/weapons/manuals.dm
Labels: Fix

#942 Add BeerBox
  code/datums/supplypacks.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/hispania/game/objects/items/weapons/storage/fancy.dm
  icons/hispania/mob/inhands/items_lefthand.dmi
  icons/hispania/mob/inhands/items_righthand.dmi
  icons/hispania/obj/food/containers.dmi
Labels: Sprites

#932 [New Planet] Naga Expanded Content
  _maps/hispania.dm
  _maps/map_files/hispania/_MAP_DEFINES.dm
  _maps/map_files/hispania/hispania.dmm
  _maps/map_files/hispania/z2.dmm
  _maps/map_files/hispania/z4.dmm
  code/game/gamemodes/game_mode.dm
  code/hispania/game/area/Space Station 13 areas.dm
  code/hispania/game/machinery/computer/computer.dm
  code/hispania/game/objects/effects/spawners/decals/misc.dm
  code/hispania/game/objects/effects/spawners/mapping_helpers.dm
  code/hispania/game/objects/items/weapons/notes.dm
  code/hispania/game/objects/structures/flora.dm
  code/hispania/game/objects/structures/mineral_doors.dm
  code/hispania/game/objects/structures/spawner.dm
  code/hispania/game/turf/hispania_floor.dm
  code/hispania/modules/mob/living/simple_animal/hostile/netherworld.dm
  code/hispania/modules/shuttle/shuttle.dm
  code/hispania/modules/station_goals/redspacedisk.dm
  icons/hispania/mob/animals.dmi
  icons/hispania/obj/doors.dmi
  icons/hispania/obj/flora/flora_snow.dmi
  icons/hispania/obj/flora/small_flora_snow.dmi
  icons/hispania/obj/machines/research.dmi
  icons/hispania/turf/ice_turfs.dmi
  icons/hispania/turf/misc.dmi
  icons/hispania/turf/snow.dmi
  icons/hispania/turf/walls.dmi
  paradise.dme
Labels: Feature

#945 Fix Free Clothing en algunas vendings
  code/hispania/game/machinery/vending.dm
Labels: Fix

#910 Add Traits (-5-Positive/-1-Neutral/-7-Negative) 15 Total
  code/hispania/datums/traits/negative.dm
  code/hispania/datums/traits/neutral.dm
  code/hispania/datums/traits/positive.dm
Labels: Traits

#944 TRAITS UPDATE | +4 Positives + 3 Negatives | Contacto Visual
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/traits.dm
  code/hispania/datums/traits/negative.dm
  code/hispania/datums/traits/neutral.dm
  code/hispania/datums/traits/positive.dm
  code/hispania/modules/mob/mob.dm
  code/modules/admin/verbs/pray.dm
  code/modules/client/client_defines.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/gun.dm
  paradise.dme
Labels: Destruyendo la necesidad de ser bilingüe, Port, Traits

#952 Fix a sprites de armas y retoques
  code/hispania/modules/projectiles/projectiles/beams.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  icons/hispania/obj/guns/energy.dmi
  icons/hispania/obj/guns/projectile.dmi
  icons/hispania/obj/projectiles.dmi
Labels: Fix, Sprites, Tweak

#956 Fix Runtimes Z4-Z6
  _maps/base_map.dm
  code/game/world.dm
  code/modules/space_management/level_traits.dm
  paradise.dme
Labels: Fix

#953 traduccion del voice of god
  code/hispania/modules/surgery/organs/vocal_cords.dm
  code/modules/surgery/organs/vocal_cords.dm
  paradise.dme
Labels: Destruyendo la necesidad de ser bilingüe

#957 Quirks visibles en medical records
  code/hispania/controllers/subsystem/processing/quirks.dm
  code/hispania/datums/traits/_quirk.dm
Labels: Fix

#960 [Map Changes] Hispania y Lavaland Estándar
  _maps/map_files/hispania/Lavaland.dmm
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes

#962 [Map Changes] Delta Estándar
  _maps/map_files/Delta/delta.dmm
Labels: Map changes

#958 Fix Auto Belt
  code/hispania/modules/crafting/recipes.dm
Labels: Fix

#964 [Map Changes] Dababy Estandar
  _maps/map_files/dababy/sexo.dmm
  code/modules/client/asset_cache.dm
  code/modules/mapping/dababy.dm
  icons/_nanomaps/Dababy_nanomap_z1.png
  tools/github-actions/nanomap-renderer-invoker.sh
Labels: Futuro de Hispania, Map changes

#963 [Map Changes] Reparaciones mas a delta.
  _maps/map_files/Delta/delta.dmm
Labels: Map changes

#965 Arreglando el cableado en inge
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes

#966 NEW SPRITES BABY: Colossus y Legion
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  icons/hispania/mob/lavaland/96x96megafauna.dmi
  icons/hispania/mob/lavaland/legion.dmi
Labels: Port, Sprites

#968 [Map Changes] Delta Estandar
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map changes

#961 Añade la función de craftear medkits
  code/hispania/modules/crafting/recipes.dm
Labels: Tweak

#959 Security Records REWORK
  code/datums/datacore.dm
  code/defines/procs/records.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/doors/brigdoors.dm
  code/hispania/game/machinery/doors/brigdoors_crimes.dm
  paradise.dme
  tgui/packages/tgui/interfaces/BrigTimer.js
  tgui/packages/tgui/interfaces/Crimes.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Hispania TGUI, Tweak
