Repository Helixis/Paradise, pull requests merged in 2021-08, with the labels that each got.

#1040 Comimix
  code/hispania/game/machinery/vending.dm
  code/hispania/game/objects/items/weapons/kitchen.dm
  code/hispania/game/objects/items/weapons/storage/toolbox.dm
  code/hispania/modules/client/preference/loadout/loadout_general.dm
  code/hispania/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/hispania/modules/reagents/chemistry/reagents/alcohol.dm
  icons/hispania/mob/inhands/items_lefthand.dmi
  icons/hispania/mob/inhands/items_righthand.dmi
  icons/hispania/mob/inhands/toolbox_lefthand.dmi
  icons/hispania/mob/inhands/toolbox_righthand.dmi
  icons/hispania/obj/drinks.dmi
  icons/hispania/obj/kitchen.dmi
  icons/hispania/obj/storage.dmi
  paradise.dme
Labels: Feature, nom nom nom

#1053 Tweak Delay a respawn
  code/modules/mob/mob.dm
Labels: Tweak

#1057 Add Skill System (Metaconocimientos)
  code/__HELPERS/unsorted.dm
  code/datums/outfits/outfit.dm
  code/datums/skills.dm
  code/game/jobs/job/medical.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/computer/cloning.dm
  code/game/mecha/mech_fabricator.dm
  code/hispania/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/chem_heater.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/research/rdconsole.dm
  paradise.dme
Labels: Feature
