Repository Helixis/Paradise, pull requests merged in 2021-12, with the labels that each got.

#1114 Risas independientes y quirk risa malefica
  code/__HELPERS/traits.dm
  code/hispania/datums/traits/positive.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species/_species.dm
  sound/hispania/voice/human/manlaugh_evil.ogg
  sound/hispania/voice/human/womanlaugh_evil.ogg
Labels: Tweak, Sound, Traits

#1116 Traduccion traders sol gov
  code/modules/events/traders.dm
Labels: Destruyendo la necesidad de ser bilingüe

#1124 Modo de juego Extended Anarchy [MDB IGNORE] [IDB IGNORE]
  code/hispania/game/gamemodes/extendedanarchy/anarchymode.dm
  config/example/config.toml
Labels: GAMEMODE, Héroe de Hispania

#1125 Anarchymode [MDB IGNORE] [IDB IGNORE]
  code/hispania/game/gamemodes/anarchy/anarchymode.dm
  paradise.dme
Labels: GAMEMODE

#1120 Quita las razas prohibidas de la lista.
  code/modules/mob/living/carbon/human/species/kidan.dm
  code/modules/mob/living/carbon/human/species/nucleation.dm
  code/modules/mob/living/carbon/human/species/vox.dm
  code/modules/mob/living/carbon/human/species/wryn.dm
Labels: Tweak, Reconstruyendo la sociedad de nuevo

#1133 SQL EPIC FAIL FIXER 5000
  code/modules/client/preference/character.dm
Labels: Fix, SQL

#1135 Fix Locker Arrival Sprite
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
Labels: Fix

#1149 Alt jobs desde la consola del hop
  code/game/machinery/computer/card.dm
Labels: Tweak

#1153 Nuevo Evento random. Feed me! [TERMINADO]
  _maps/map_files/dababy/sexo2.dmm
  _maps/map_files/hispania/hispania.dmm
  _maps/map_files/hispania/retro_hispania.dmm
  code/__DEFINES/mobs.dm
  code/_globalvars/mapping.dm
  code/game/objects/effects/landmarks.dm
  code/hispania/modules/events/feedme.dm
  code/modules/events/event_container.dm
  code/modules/events/event_procs.dm
  code/modules/food_and_drinks/food/snacks.dm
  icons/hispania/mob/comensales.dmi
  paradise.dme
Labels: Feature

#1134 Portea el sistema de huellas y analisis del detective de aurora y RU [READY]
  _maps/map_files/dababy/sexo2.dmm
  _maps/map_files/hispania/hispania.dmm
  _maps/map_files/hispania/retro_hispania.dmm
  code/datums/supplypacks.dm
  code/game/jobs/job/security.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/items/weapons/manuals.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/detective_work/scanner.dm
  code/modules/detectivework/microscope/dnascanner.dm
  code/modules/detectivework/microscope/microscope.dm
  code/modules/detectivework/tools/crimekit.dm
  code/modules/detectivework/tools/sample_kits.dm
  code/modules/detectivework/tools/storage.dm
  code/modules/detectivework/tools/swabs.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/ammo_casings.dm
  code/modules/projectiles/ammunition/energy.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/special.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/research/designs/machine_designs.dm
  icons/obj/forensics.dmi
  paradise.dme
  sound/hispania/machines/Custom_screwdriverclose.ogg
  sound/hispania/machines/floppydisk.ogg
  sound/hispania/machines/printer.ogg
Labels: Feature, Futuro de Hispania, Testeado!

#1150 SUS Machine Prototype
  code/hispania/datums/supplypacks.dm
  code/hispania/game/objects/items/divices/syndieprototype.dm
  icons/hispania/obj/syndieproto.dmi
  paradise.dme
Labels: Feature, Testeado!

#1157 Clothelate 2
  code/hispania/__DEFINES/wires.dm
  code/hispania/datums/wires/clothelate.dm
  code/hispania/game/machinery/clothelate.dm
  code/hispania/game/machinery/constructable_frame.dm
  code/hispania/modules/research/designs/clothelate_designs.dm
  code/hispania/modules/research/designs/machine_designs.dm
  code/modules/research/research.dm
  icons/hispania/obj/clothelate.dmi
  paradise.dme
  tgui/packages/tgui/interfaces/Clothelate.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Hispania TGUI, Testeado!
