Repository Helixis/Paradise, pull requests merged in 2021-04, with the labels that each got.

#838 Discord Mention FIX
  code/game/gamemodes/game_mode.dm
Labels: Discord, Fix

#826 Armas Re-spriteables con Menú Radial
  code/hispania/game/objects/items/radial.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  paradise.dme
Labels: Tweak

#835 La SM Update NOW REAL
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes, Tweak

#790 Nuevas WinterCoats █ Edición Seguridad || 358/2 days EDITION ||
  code/hispania/modules/client/preference/loadout/loadout_suit.dm
  code/hispania/modules/clothing/suits/winter.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/hispania/mob/head.dmi
  icons/hispania/mob/inhands/clothing_lefthand.dmi
  icons/hispania/mob/inhands/clothing_righthand.dmi
  icons/hispania/mob/species/vox/head.dmi
  icons/hispania/mob/species/vox/suit.dmi
  icons/hispania/mob/suit.dmi
  icons/hispania/obj/clothing/hats.dmi
  icons/hispania/obj/clothing/suits.dmi
  paradise.dme
Labels: Feature, Marge Conflict, Sprites, Tweak

#840 exosuit skins
  code/hispania/game/mecha/paintkits.dm
  icons/hispania/mecha/mecha.dmi
  paradise.dme
Labels: Sprites

#841 La optimización en la SM update
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes, Refactor

#843 Update mecha.dmi
  icons/mecha/mecha.dmi
Labels: Sprites

#842 Ordena Alfabéticamente las semillas de Hispania
  code/hispania/game/machinery/vending.dm
Labels: EL PR QUE HIZO LLORAR A SPILBERG, Refactor

#844 Eliminacion del multiplicador de daño
  code/modules/mob/living/carbon/human/species/machine.dm
Labels: EL PR QUE HIZO LLORAR A SPILBERG

#848 Ipc nerf
  code/hispania/datums/traits/neutral.dm
  code/modules/mob/living/carbon/human/species/machine.dm
  code/modules/surgery/organs/augments_arms.dm
Labels: Balance, Catástrofe Racial

#849 Le atmos Fix
  _maps/map_files/hispania/hispania.dmm
Labels: Fix, Map changes

#846 Buff IA - Decora Telesci - Medbay Bell
  _maps/map_files/hispania/hispania.dmm
  code/hispania/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Map changes, READY FOR REVIEW

#845 La Venganza de los monos parte 2
  code/game/objects/items/weapons/handcuffs.dm
  code/hispania/__DEFINES/monkey.dm
  code/hispania/modules/mob/living/carbon/human/species/monkey_combat.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species/monkey.dm
  code/modules/reagents/reagent_containers/syringes.dm
  paradise.dme
Labels: Catástrofe Racial, Feature, Port

#853 Añadir permisos de maint_tunnels a ciencias.
  code/game/jobs/job/science.dm
Labels: Balance

#850 Crea chem dispenser para botanica
  code/hispania/game/machinery/constructable_frame.dm
  code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/hispania/modules/research/designs/machine_designs.dm
  icons/hispania/obj/chemical.dmi
  paradise.dme
Labels: Feature, Futuro de Hispania

#855 manual de tameo de los goliath
  code/game/objects/items/weapons/storage/backpack.dm
  code/hispania/game/objects/items/weapons/manuals.dm
  code/modules/mining/machine_vending.dm
Labels: EL PR QUE HIZO LLORAR A SPILBERG, Futuro de Hispania, Priority

#857 [Map Change] Re agregar nave de mineria
  _maps/map_files/hispania/Lavaland.dmm
  _maps/map_files/hispania/hispania.dmm
Labels: Map changes

#858 Fix Cambio de alarma a comando
  tgui/packages/tgui/interfaces/CommunicationsComputer.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Fix

#860 Tweak Binocular a Belts
  code/game/objects/items/weapons/storage/belt.dm
Labels: Tweak

#859 Tweak Palabras Clave de Traitor
  code/__HELPERS/names.dm
  code/hispania/__HELPERS/names.dm
  paradise.dme
Labels: Destruyendo la necesidad de ser bilingüe, Tweak

#839 [RESPRITE] Sec Officer Blue y Red + Codigo para poner accesorios en ropas al ser creados
  code/hispania/modules/clothing/under/accessories/accessory.dm
  code/hispania/modules/clothing/under/jobs/security.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/accessories/accessory.dm
  icons/hispania/mob/head.dmi
  icons/hispania/mob/species/grey/ties.dmi
  icons/hispania/mob/species/grey/uniform.dmi
  icons/hispania/mob/species/vox/head.dmi
  icons/hispania/mob/species/vox/ties.dmi
  icons/hispania/mob/species/vox/uniform.dmi
  icons/hispania/mob/ties.dmi
  icons/hispania/mob/uniform.dmi
  icons/hispania/obj/clothing/hats.dmi
  icons/hispania/obj/clothing/ties.dmi
  icons/hispania/obj/clothing/ties_overlay.dmi
  icons/hispania/obj/clothing/uniforms.dmi
  paradise.dme
Labels: Sprites

#852 Cambios de Armas // Point Blank Knockback, Taser Delay y Feedback AUDITIVO
  code/hispania/modules/projectiles/ammo/energy.dm
  code/hispania/modules/projectiles/projectiles/energy.dm
  code/modules/mob/living/living.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/projectile/energy.dm
  paradise.dme
Labels: Feature, Port, Sound, Tweak

#856 Revert "Eliminacion del multiplicador de daño"
  code/modules/mob/living/carbon/human/species/machine.dm
Labels: EL PR QUE HIZO LLORAR A SPILBERG, Revert/Feature Removal

#863 margear si se margea #856
  code/hispania/datums/traits/neutral.dm
  code/modules/mob/living/carbon/human/species/machine.dm
  code/modules/surgery/organs/augments_arms.dm
Labels: Revert/Feature Removal

#861 Fix Pancakes
  code/hispania/modules/food_and_drinks/food/foods/baked_goods.dm
  code/hispania/modules/food_and_drinks/recipes/recipes_oven.dm
Labels: Fix

#862 Add Hand-Made Splint
  code/hispania/game/objects/items/divices/stacks/medical.dm
  code/hispania/modules/crafting/recipes.dm
  icons/hispania/obj/miscellaneous.dmi
  paradise.dme
Labels: Feature

#864 Add Comida Enlatada
  code/game/objects/effects/spawners/lootdrop.dm
  code/hispania/datums/supplypacks.dm
  code/hispania/game/objects/effects/spawners/lootdrop.dm
  code/hispania/game/objects/items/trash.dm
  code/hispania/modules/food_and_drinks/food/foods/canned_food.dm
  icons/hispania/obj/food/canned_food.dmi
  icons/hispania/obj/trash.dmi
  paradise.dme
Labels: Feature, Sprites

#867 [Map Change] Pequeñas reparaciones a la hispania.
  _maps/map_files/hispania/hispania.dmm
Labels: Fix, Map changes

#868 Fix Alarmas de Anomalias
  code/game/objects/effects/anomalies.dm
Labels: Fix
