Repository Helixis/Paradise, pull requests merged in 2021-11, with the labels that each got.

#1095 [FIXES] Remueve todas las razas excepto IPC y Humano del Codigo, siendo estas ahora injugables totalmente
  code/game/gamemodes/traitor/traitor.dm
Labels: Fix

#1092 Nerf Swarmers
  code/game/gamemodes/miniantags/bot_swarm/swarmer.dm
Labels: Balance

#1097 Fix vendings
  code/game/machinery/vending.dm
Labels: Fix

#1096 Swat4, El PR obligatorio anual de re-sprites al riot suit
  code/hispania/game/objects/items/weapons/shields.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  icons/hispania/mob/back.dmi
  icons/hispania/mob/head.dmi
  icons/hispania/mob/inhands/clothing_lefthand.dmi
  icons/hispania/mob/inhands/clothing_righthand.dmi
  icons/hispania/mob/inhands/items_lefthand.dmi
  icons/hispania/mob/inhands/items_righthand.dmi
  icons/hispania/mob/suit.dmi
  icons/hispania/obj/clothing/hats.dmi
  icons/hispania/obj/clothing/suits.dmi
  icons/hispania/obj/items.dmi
  icons/mob/clothing/back.dmi
Labels: Tweak, Sprites, Fix

#1101 vuelve la soga para ahorcarse
  code/modules/power/cable.dm
Labels: Reconstruyendo la sociedad de nuevo

#1099 Vuelven los sonidos emote, y se agregan otros nuevos
  code/game/machinery/door_control.dm
  code/game/machinery/recharger.dm
  code/modules/admin/topic.dm
  code/modules/food_and_drinks/food/foods/misc.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species/_species.dm
  code/modules/security_levels/keycard_authentication.dm
  sound/hispania/machines/button.ogg
  sound/hispania/machines/keycard_denied.ogg
  sound/hispania/machines/keycard_succes.ogg
  sound/hispania/machines/reloading_charger.ogg
  sound/hispania/misc/monke.ogg
  sound/hispania/misc/monke_eat.ogg
  sound/hispania/voice/human/manlaugh2.ogg
  sound/hispania/voice/human/manlaugh3.ogg
  sound/hispania/voice/human/manlaugh4.ogg
  sound/hispania/voice/human/womanlaugh2.ogg
Labels: Sound, Reconstruyendo la sociedad de nuevo

#1098 [FIXES]Arregla error de drone invisible
  icons/mob/robots.dmi
Labels: CASO CERRADO

#1107 Pull Request Hispanification
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Destruyendo la necesidad de ser bilingüe

#1093 Nuevo Z level!
  _maps/map_files/RandomZLevels/zNica.dmm
  code/_globalvars/lists/objects.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/structures/misc.dm
  icons/obj/lever.dmi
  sound/hispania/misc/palanca.ogg
Labels: Feature, Sprites

#1112 trajes enfermera loadout
  code/hispania/modules/client/preference/loadout/loadout_uniform.dm
Labels: Tweak

#1111 El mejor PR de Hispania - Full Auto Fix
  code/hispania/datums/autofiresystem.dm
  code/hispania/game/objects/items.dm
  code/hispania/modules/projectiles/guns/fullauto.dm
  code/hispania/modules/projectiles/guns/projectile/natasha.dm
  code/modules/mob/inventory.dm
  code/modules/projectiles/gun.dm
Labels: Tweak, Fix, Futuro de Hispania

#1110 Sube de plano los mensajes del runechat
  code/datums/chatmessage.dm
Labels: Tweak

#1108 Arreglos a LeBaby
  _maps/map_files/dababy/sexo2.dmm
Labels: Fix

#1109 Airlocks Tile Update
  code/_onclick/click.dm
  code/game/turfs/turf.dm
Labels: Tweak

#1106 Crossbreeding de Chilling Blue
  code/hispania/modules/research/xenobiology/crossbreeding/_clothing.dm
  code/hispania/modules/research/xenobiology/crossbreeding/burning.dm
  code/hispania/modules/research/xenobiology/crossbreeding/chilling.dm
Labels: Feature, Tweak
